///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Landing.Catalogs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Catalogs_ChangeCatalog recording.
    /// </summary>
    [TestModule("d8b50200-7f3e-40a2-bfe7-c4dcb54827ad", ModuleType.Recording, 1)]
    public partial class Catalogs_ChangeCatalog : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Catalogs_ChangeCatalog instance = new Catalogs_ChangeCatalog();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Catalogs_ChangeCatalog()
        {
            Catalog2Title = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Catalogs_ChangeCatalog Instance
        {
            get { return instance; }
        }

#region Variables

        string _Catalog2Title;

        /// <summary>
        /// Gets or sets the value of variable Catalog2Title.
        /// </summary>
        [TestVariable("c74b0e37-6836-46fa-9ddb-67d199e3a542")]
        public string Catalog2Title
        {
            get { return _Catalog2Title; }
            set { _Catalog2Title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.BtnBrowse' at Center", repo.PlusSparSi.MainActivity.BtnBrowseInfo, new RecordItemIndex(0));
            repo.PlusSparSi.MainActivity.BtnBrowse.Touch();
            Delay.Milliseconds(500);
            
            CheckIfMultipleCatalogs();
            Delay.Milliseconds(0);
            
            OpenCatalogSelection();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
