///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Landing.Catalogs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Catalog_CheckItems_CatalogNum recording.
    /// </summary>
    [TestModule("123236bf-d451-4233-a509-8c549a048c85", ModuleType.Recording, 1)]
    public partial class Catalog_CheckItems_CatalogNum : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Catalog_CheckItems_CatalogNum instance = new Catalog_CheckItems_CatalogNum();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Catalog_CheckItems_CatalogNum()
        {
            accessToken = "";
            catalogNum = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Catalog_CheckItems_CatalogNum Instance
        {
            get { return instance; }
        }

#region Variables

        string _accessToken;

        /// <summary>
        /// Gets or sets the value of variable accessToken.
        /// </summary>
        [TestVariable("a33fe5c3-eb05-43c0-8c72-cfecaf95e468")]
        public string accessToken
        {
            get { return _accessToken; }
            set { _accessToken = value; }
        }

        string _catalogNum;

        /// <summary>
        /// Gets or sets the value of variable catalogNum.
        /// </summary>
        [TestVariable("534276be-f600-40f6-bf3c-4538a0a7023c")]
        public string catalogNum
        {
            get { return _catalogNum; }
            set { _catalogNum = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CheckNumOfCatalogs();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.BtnBrowse' at Center", repo.PlusSparSi.MainActivity.BtnBrowseInfo, new RecordItemIndex(1));
            repo.PlusSparSi.MainActivity.BtnBrowse.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$catalogNum) on item 'PlusSparSi.MainActivity.MenuBadge'.", repo.PlusSparSi.MainActivity.MenuBadgeInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MenuBadgeInfo, "Text", catalogNum);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.NavigateUp' at Center", repo.PlusSparSi.MainActivity.NavigateUpInfo, new RecordItemIndex(3));
            repo.PlusSparSi.MainActivity.NavigateUp.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
