///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Landing.Catalogs
{
	public partial class Catalogs_ChangeCatalog
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		/// 
		public bool multipleCatalogs;
		
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void CheckIfMultipleCatalogs()
		{
			repo.PlusSparSi.SearchTimeout = new Duration(1000);
			repo.PlusSparSi.MainActivity.SearchTimeout = new Duration(1000);
			repo.PlusSparSi.MainActivity.MenuBadgeInfo.SearchTimeout = new Duration(1500);
			
			multipleCatalogs = repo.PlusSparSi.MainActivity.MenuBadgeInfo.Exists();
			
		}

		public void OpenCatalogSelection()
		{
			if(multipleCatalogs){
				
				Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MenuBadge' at Center", repo.PlusSparSi.MainActivity.MenuBadgeInfo, new RecordItemIndex(3));
				repo.PlusSparSi.MainActivity.MenuBadge.Touch();
				Delay.Milliseconds(500);
				
				Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'PlusSparSi.MainActivity.News2_Title' and assigning its value to variable 'Catalog2Title'.", repo.PlusSparSi.MainActivity.News2_TitleInfo, new RecordItemIndex(3));
				Catalog2Title = repo.PlusSparSi.MainActivity.News2_Title.Element.GetAttributeValueText("Text");
				Delay.Milliseconds(0);
				
				Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.News2_Title' at Center", repo.PlusSparSi.MainActivity.News2_TitleInfo, new RecordItemIndex(3));
				repo.PlusSparSi.MainActivity.News2_Title.Touch();
				Delay.Milliseconds(500);
				
				Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Catalog2Title) on item 'PlusSparSi.MainActivity.RStringTabTitle'.", repo.PlusSparSi.MainActivity.RStringTabTitleInfo, new RecordItemIndex(3));
				Validate.Attribute(repo.PlusSparSi.MainActivity.RStringTabTitleInfo, "Text", Catalog2Title);
				Delay.Milliseconds(0);
			}
		}
	}
}
