///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The iOS_NoCard_Registration_Success recording.
    /// </summary>
    [TestModule("81b4ca1d-2c8b-4ed3-8bc7-111c9c666dd4", ModuleType.Recording, 1)]
    public partial class IOS_NoCard_Registration_Success : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static IOS_NoCard_Registration_Success instance = new IOS_NoCard_Registration_Success();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IOS_NoCard_Registration_Success()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IOS_NoCard_Registration_Success Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Pričnite tako, da skenirate svojo SPAR plus kartico!') on item 'ComInovaintSpar.Registration.LandingScreen.PričniteTakoDaSkenirateSvojoSPARP'.", repo.ComInovaintSpar.Registration.LandingScreen.PričniteTakoDaSkenirateSvojoSPARPInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.ComInovaintSpar.Registration.LandingScreen.PričniteTakoDaSkenirateSvojoSPARPInfo, "Caption", "Pričnite tako, da skenirate svojo SPAR plus kartico!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.LandingScreen.NimamSPARPlusKartice' at Center", repo.ComInovaintSpar.Registration.LandingScreen.NimamSPARPlusKarticeInfo, new RecordItemIndex(1));
            repo.ComInovaintSpar.Registration.LandingScreen.NimamSPARPlusKartice.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Postani član SPAR plus') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.PostaniČlanSPARPlus'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PostaniČlanSPARPlusInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PostaniČlanSPARPlusInfo, "Caption", "Postani član SPAR plus");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Ekskluzivni kuponi in ugodnosti') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.EkskluzivniKuponiInUgodnosti'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.EkskluzivniKuponiInUgodnostiInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.EkskluzivniKuponiInUgodnostiInfo, "Caption", "Ekskluzivni kuponi in ugodnosti");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Zbiranje dobropisa na kartici') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.ZbiranjeDobropisaNaKartici'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.ZbiranjeDobropisaNaKarticiInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.ZbiranjeDobropisaNaKarticiInfo, "Caption", "Zbiranje dobropisa na kartici");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Dostop do SPAR plus kartice kar na telefonu') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.DostopDoSPARPlusKarticeKarNaTelef'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.DostopDoSPARPlusKarticeKarNaTelefInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.DostopDoSPARPlusKarticeKarNaTelefInfo, "Caption", "Dostop do SPAR plus kartice kar na telefonu");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_NoCard_Join.PridružiteSe' at Center", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PridružiteSeInfo, new RecordItemIndex(6));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PridružiteSe.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Domen' on item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Ime'.", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.ImeInfo, new RecordItemIndex(7));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Ime.Element.SetAttributeValue("Text", "Domen");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Fras' on item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Priimek'.", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.PriimekInfo, new RecordItemIndex(8));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Priimek.Element.SetAttributeValue("Text", "Fras");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '13.01.1988' on item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.DatumRojstva'.", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.DatumRojstvaInfo, new RecordItemIndex(9));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.DatumRojstva.Element.SetAttributeValue("Text", "13.01.1988");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Spol' at Center", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.SpolInfo, new RecordItemIndex(10));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Spol.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Moški' at Center", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.MoškiInfo, new RecordItemIndex(11));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Moški.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(12));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Vpišite podatke o prebivališču') on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.VpišitePodatkeOPrebivališču'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.VpišitePodatkeOPrebivališčuInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Address.VpišitePodatkeOPrebivališčuInfo, "Caption", "Vpišite podatke o prebivališču");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Slovenija' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.Država'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.DržavaInfo, new RecordItemIndex(14));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.Država.Element.SetAttributeValue("Text", "Slovenija");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Cirknica' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.Ulica'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.UlicaInfo, new RecordItemIndex(15));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.Ulica.Element.SetAttributeValue("Text", "Cirknica");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '26' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.HišnaŠtevilka'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.HišnaŠtevilkaInfo, new RecordItemIndex(16));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.HišnaŠtevilka.Element.SetAttributeValue("Text", "26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '2212' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.PoštnaŠtevilka'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.PoštnaŠtevilkaInfo, new RecordItemIndex(17));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.PoštnaŠtevilka.Element.SetAttributeValue("Text", "2212");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Šentilj' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.Kraj'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.KrajInfo, new RecordItemIndex(18));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.Kraj.Element.SetAttributeValue("Text", "Šentilj");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComInovaintSpar'.", repo.ComInovaintSpar.SelfInfo, new RecordItemIndex(19));
            repo.ComInovaintSpar.Self.PressKeys("{ENTER}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(20));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Vpišite podatke za prijavo') on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.VpišitePodatkeZaPrijavo'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.VpišitePodatkeZaPrijavoInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Data.VpišitePodatkeZaPrijavoInfo, "Caption", "Vpišite podatke za prijavo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '040305750' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.ŠtevilkaMobilnegaTelefona'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.ŠtevilkaMobilnegaTelefonaInfo, new RecordItemIndex(22));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.ŠtevilkaMobilnegaTelefona.Element.SetAttributeValue("Text", "040305750");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'domen.fras@gmail.com' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.EMailNaslov'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.EMailNaslovInfo, new RecordItemIndex(23));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.EMailNaslov.Element.SetAttributeValue("Text", "domen.fras@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Adgjadgj1' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.Geslo'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.GesloInfo, new RecordItemIndex(24));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.Geslo.Element.SetAttributeValue("Text", "Adgjadgj1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Adgjadgj1' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.PonoviGeslo'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.PonoviGesloInfo, new RecordItemIndex(25));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.PonoviGeslo.Element.SetAttributeValue("Text", "Adgjadgj1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComInovaintSpar'.", repo.ComInovaintSpar.SelfInfo, new RecordItemIndex(26));
            repo.ComInovaintSpar.Self.PressKeys("{ENTER}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(27));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Dodatne informacije') on item 'ComInovaintSpar.Registration.Registration_NoCard_AdditionalData.DodatneInformacije'.", repo.ComInovaintSpar.Registration.Registration_NoCard_AdditionalData.DodatneInformacijeInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_AdditionalData.DodatneInformacijeInfo, "Caption", "Dodatne informacije");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(29));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Ne spreglejte kuponov in promocij') on item 'ComInovaintSpar.Registration.Registration_Permissions.Permissions_CommonElements.NeSpreglejteKuponovInPromocij'.", repo.ComInovaintSpar.Registration.Registration_Permissions.Permissions_CommonElements.NeSpreglejteKuponovInPromocijInfo, new RecordItemIndex(30));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_Permissions.Permissions_CommonElements.NeSpreglejteKuponovInPromocijInfo, "Caption", "Ne spreglejte kuponov in promocij");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Preskoči' at Center", repo.ComInovaintSpar.Registration.CommonElements.PreskočiInfo, new RecordItemIndex(31));
            repo.ComInovaintSpar.Registration.CommonElements.Preskoči.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Kje je najbližji Spar?') on item 'ComInovaintSpar.Registration.Registration_Permissions.Permission_Location.KjeJeNajbližjiSpar'.", repo.ComInovaintSpar.Registration.Registration_Permissions.Permission_Location.KjeJeNajbližjiSparInfo, new RecordItemIndex(32));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_Permissions.Permission_Location.KjeJeNajbližjiSparInfo, "Caption", "Kje je najbližji Spar?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Preskoči' at Center", repo.ComInovaintSpar.Registration.CommonElements.PreskočiInfo, new RecordItemIndex(33));
            repo.ComInovaintSpar.Registration.CommonElements.Preskoči.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_Permissions.SparCardAlwaysAccessible.Dokončaj' at Center", repo.ComInovaintSpar.Registration.Registration_Permissions.SparCardAlwaysAccessible.DokončajInfo, new RecordItemIndex(34));
            repo.ComInovaintSpar.Registration.Registration_Permissions.SparCardAlwaysAccessible.Dokončaj.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
