///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The iOS_NoCard_Registration_Success recording.
    /// </summary>
    [TestModule("81b4ca1d-2c8b-4ed3-8bc7-111c9c666dd4", ModuleType.Recording, 1)]
    public partial class IOS_NoCard_Registration_Success : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static IOS_NoCard_Registration_Success instance = new IOS_NoCard_Registration_Success();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IOS_NoCard_Registration_Success()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IOS_NoCard_Registration_Success Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Pričnite tako, da skenirate svojo SPAR plus kartico!') on item 'ComInovaintSpar.NoCardRegistrationScreens.PričniteTakoDaSkenirateSvojoSPARP'.", repo.ComInovaintSpar.NoCardRegistrationScreens.PričniteTakoDaSkenirateSvojoSPARPInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.ComInovaintSpar.NoCardRegistrationScreens.PričniteTakoDaSkenirateSvojoSPARPInfo, "Caption", "Pričnite tako, da skenirate svojo SPAR plus kartico!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Ste pri skeniranju naleteli na težave?') on item 'ComInovaintSpar.NoCardRegistrationScreens.StePriSkeniranjuNaleteliNaTežave'.", repo.ComInovaintSpar.NoCardRegistrationScreens.StePriSkeniranjuNaleteliNaTežaveInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.ComInovaintSpar.NoCardRegistrationScreens.StePriSkeniranjuNaleteliNaTežaveInfo, "Caption", "Ste pri skeniranju naleteli na težave?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.NoCardRegistrationScreens.NimamSPARPlusKartice' at Center", repo.ComInovaintSpar.NoCardRegistrationScreens.NimamSPARPlusKarticeInfo, new RecordItemIndex(2));
            repo.ComInovaintSpar.NoCardRegistrationScreens.NimamSPARPlusKartice.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
