///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Registration
{
    public partial class Registration_Success
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Test()
        {
            // TODO: Replace the following line with your code implementation.
            throw new NotImplementedException();
        }

        public void Touch_SwShowOnlyOpen(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'buttonInfo' at 26;64", buttonInfo);
            buttonInfo.FindAdapter<Button>().Touch("26;64");
        }

        public void Registration_Success_Run_Mobile_App()
        {
            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'plus.spar.si' on device 'Sony'.");
            Host.Local.RunMobileApp("Sony", "plus.spar.si", true);
        }
               	

    }
}
