///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Registration_Success recording.
    /// </summary>
    [TestModule("3b5eaeef-79af-4751-be86-63848da88ff6", ModuleType.Recording, 1)]
    public partial class Registration_Success : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Registration_Success instance = new Registration_Success();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Registration_Success()
        {
            Name = "";
            Surname = "";
            DateOfBirth = "";
            Country = "";
            Address = "";
            PostalNumber = "";
            City = "";
            PhoneNumber = "";
            Email = "";
            Password = "";
            Gender = "";
            HouseNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Registration_Success Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("ba843f94-a98f-40c9-b273-2deef2a1f056")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        string _Surname;

        /// <summary>
        /// Gets or sets the value of variable Surname.
        /// </summary>
        [TestVariable("212de63e-4181-448a-b359-07c10def87b4")]
        public string Surname
        {
            get { return _Surname; }
            set { _Surname = value; }
        }

        string _DateOfBirth;

        /// <summary>
        /// Gets or sets the value of variable DateOfBirth.
        /// </summary>
        [TestVariable("9d01736c-c8c9-4490-a510-6160f378bbdb")]
        public string DateOfBirth
        {
            get { return _DateOfBirth; }
            set { _DateOfBirth = value; }
        }

        string _Country;

        /// <summary>
        /// Gets or sets the value of variable Country.
        /// </summary>
        [TestVariable("f78c676b-e99f-4d90-a462-fe331b5b7949")]
        public string Country
        {
            get { return _Country; }
            set { _Country = value; }
        }

        string _Address;

        /// <summary>
        /// Gets or sets the value of variable Address.
        /// </summary>
        [TestVariable("a8aac716-de1a-454a-bb1c-d89868ae7bb5")]
        public string Address
        {
            get { return _Address; }
            set { _Address = value; }
        }

        string _PostalNumber;

        /// <summary>
        /// Gets or sets the value of variable PostalNumber.
        /// </summary>
        [TestVariable("1b5cd7d8-a8b1-4442-a67b-1edec64b1d5c")]
        public string PostalNumber
        {
            get { return _PostalNumber; }
            set { _PostalNumber = value; }
        }

        string _City;

        /// <summary>
        /// Gets or sets the value of variable City.
        /// </summary>
        [TestVariable("7f104a17-a1f2-4fc4-a4d5-662e21c23529")]
        public string City
        {
            get { return _City; }
            set { _City = value; }
        }

        string _PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable PhoneNumber.
        /// </summary>
        [TestVariable("832dd344-3eb2-4a0a-b812-ce3e0c3bdb08")]
        public string PhoneNumber
        {
            get { return _PhoneNumber; }
            set { _PhoneNumber = value; }
        }

        string _Email;

        /// <summary>
        /// Gets or sets the value of variable Email.
        /// </summary>
        [TestVariable("0ed279af-b285-427f-9acb-737d265e44a3")]
        public string Email
        {
            get { return _Email; }
            set { _Email = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("1a83f61b-162e-434a-a301-703224e1610f")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        string _HouseNumber;

        /// <summary>
        /// Gets or sets the value of variable HouseNumber.
        /// </summary>
        [TestVariable("a5038dd5-02f8-499d-8675-06c22162e3aa")]
        public string HouseNumber
        {
            get { return _HouseNumber; }
            set { _HouseNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("599c5c46-e674-4ec7-8e7a-97ff7fd23c59")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.ScanCardActivity.BtnNoCard' at Center", repo.PlusSparSi.ScanCardActivity.BtnNoCardInfo, new RecordItemIndex(0));
            repo.PlusSparSi.ScanCardActivity.BtnNoCard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterWelcomeActivity.BtnJoin' at Center", repo.PlusSparSi.RegisterWelcomeActivity.BtnJoinInfo, new RecordItemIndex(1));
            repo.PlusSparSi.RegisterWelcomeActivity.BtnJoin.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Name' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtName'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtNameInfo, new RecordItemIndex(2));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtName.Element.SetAttributeValue("Text", Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Surname' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtSurname'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtSurnameInfo, new RecordItemIndex(3));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtSurname.Element.SetAttributeValue("Text", Surname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth' at Center", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirthInfo, new RecordItemIndex(4));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.Button1' at Center", repo.PlusSparSi.Button1Info, new RecordItemIndex(5));
            repo.PlusSparSi.Button1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$DateOfBirth' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirthInfo, new RecordItemIndex(6));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth.Element.SetAttributeValue("Text", DateOfBirth);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtGender' at Center", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtGenderInfo, new RecordItemIndex(7));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtGender.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.PopUp' at Center", repo.PlusSparSi.PopUpInfo, new RecordItemIndex(8));
            repo.PlusSparSi.PopUp.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep1PersonalDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep1PersonalDataActivity.BtnNextInfo, new RecordItemIndex(9));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry' at Center", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountryInfo, new RecordItemIndex(10));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Country' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountryInfo, new RecordItemIndex(11));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry.Element.SetAttributeValue("Text", Country);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet' at Center", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreetInfo, new RecordItemIndex(12));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Address' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreetInfo, new RecordItemIndex(13));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet.Element.SetAttributeValue("Text", Address);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$HouseNumber' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumber'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumberInfo, new RecordItemIndex(14));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumber.Element.SetAttributeValue("Text", HouseNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$PostalNumber' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtPostal'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtPostalInfo, new RecordItemIndex(15));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtPostal.Element.SetAttributeValue("Text", PostalNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$City' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCity'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCityInfo, new RecordItemIndex(16));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCity.Element.SetAttributeValue("Text", City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep2ResidentDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep2ResidentDataActivity.BtnNextInfo, new RecordItemIndex(17));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Set_Value_EtPhoneNumber(repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumberInfo);
            Delay.Milliseconds(0);
            
            Set_Value_EtEmail(repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(20));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPassword'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordInfo, new RecordItemIndex(21));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPassword.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeat'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeatInfo, new RecordItemIndex(22));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeat.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(24));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch Gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '1.0' with swipe duration'500ms' and step count '0' on item 'PlusSparSi.RegisterStep4AdditionalDataActivity'.", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SelfInfo, new RecordItemIndex(25));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.Self.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "1.0"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep4AdditionalDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.BtnNextInfo, new RecordItemIndex(26));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Validate_LoginEmailSentActivity(repo.PlusSparSi.LoginEmailSentActivity.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.LoginEmailSentActivity.BtnEmailSentSkip' at Center", repo.PlusSparSi.LoginEmailSentActivity.BtnEmailSentSkipInfo, new RecordItemIndex(28));
            repo.PlusSparSi.LoginEmailSentActivity.BtnEmailSentSkip.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'PlusSparSi.OnBoardingStepOneActivity'.", repo.PlusSparSi.OnBoardingStepOneActivity.SelfInfo, new RecordItemIndex(29));
            Validate.Attribute(repo.PlusSparSi.OnBoardingStepOneActivity.SelfInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
