///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Registration
{
    public partial class Registration_SkipStep3
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
        String ID = null;
        
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Set_Value_EtEmail(RepoItemInfo textInfo)
        {
			StreamReader inputStream;
			try
			{
				inputStream = new StreamReader(File.OpenRead("RegistrationLog.csv"));
				
				String data = File.ReadLines("RegistrationLog.csv").Last(); // Read last line
				String[] values = data.Split(','); // Split the line to an array

				ID = values[0];
				ID = (int.Parse(ID) + 1) + "";
				
				String[] emailSplit = Email.Split('@');
				Email = emailSplit[0] + ID + "@" + emailSplit[1];
				
				Report.Log(ReportLevel.Info, "Email", Email);
				Report.Log(ReportLevel.Info, "ID", ID);
				
				Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Email' on item 'textInfo'.", textInfo);
				textInfo.FindAdapter<Text>().Element.SetAttributeValue("Text", Email);
				
				inputStream.Close();
				
			}catch (Exception e)
			{
				// TODO Auto-generated catch block
				Report.Log(ReportLevel.Error, "Email: " + Email, e.Message);
			}
        }

    }
}
