///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Step3_Email_Invalid recording.
    /// </summary>
    [TestModule("ac1b41f5-8c19-4ef8-bc96-44445654c96d", ModuleType.Recording, 1)]
    public partial class Step3_Email_Invalid : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Step3_Email_Invalid instance = new Step3_Email_Invalid();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Step3_Email_Invalid()
        {
            Name = "";
            Surname = "";
            DateOfBirth = "";
            Gender = "";
            Country = "";
            Address = "";
            HouseNumber = "";
            PostalNumber = "";
            City = "";
            PhoneNumber = "";
            Password = "";
            Email = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Step3_Email_Invalid Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("7f664edd-e2d6-4aa3-9b60-c7748501d475")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        string _Surname;

        /// <summary>
        /// Gets or sets the value of variable Surname.
        /// </summary>
        [TestVariable("113382b8-4d8d-42ec-8568-30f4c809c181")]
        public string Surname
        {
            get { return _Surname; }
            set { _Surname = value; }
        }

        string _DateOfBirth;

        /// <summary>
        /// Gets or sets the value of variable DateOfBirth.
        /// </summary>
        [TestVariable("65cb18f4-88f7-48fb-b878-0ace1ff7724d")]
        public string DateOfBirth
        {
            get { return _DateOfBirth; }
            set { _DateOfBirth = value; }
        }

        string _Gender;

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("3bd3ed8e-bdc2-4e4c-8043-705b5874db68")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _Country;

        /// <summary>
        /// Gets or sets the value of variable Country.
        /// </summary>
        [TestVariable("da3661be-a7e4-4d6b-aed7-9b6d80d572e2")]
        public string Country
        {
            get { return _Country; }
            set { _Country = value; }
        }

        string _Address;

        /// <summary>
        /// Gets or sets the value of variable Address.
        /// </summary>
        [TestVariable("41cb6a7e-2b9a-4124-8ba5-4db1050fbd4b")]
        public string Address
        {
            get { return _Address; }
            set { _Address = value; }
        }

        string _HouseNumber;

        /// <summary>
        /// Gets or sets the value of variable HouseNumber.
        /// </summary>
        [TestVariable("b5ef7611-11c2-40cf-a49f-a11f0d79b635")]
        public string HouseNumber
        {
            get { return _HouseNumber; }
            set { _HouseNumber = value; }
        }

        string _PostalNumber;

        /// <summary>
        /// Gets or sets the value of variable PostalNumber.
        /// </summary>
        [TestVariable("925aba7f-1174-4c06-9268-cefff67b4750")]
        public string PostalNumber
        {
            get { return _PostalNumber; }
            set { _PostalNumber = value; }
        }

        string _City;

        /// <summary>
        /// Gets or sets the value of variable City.
        /// </summary>
        [TestVariable("27f187b1-d37e-4cea-83ab-01afb5e922c3")]
        public string City
        {
            get { return _City; }
            set { _City = value; }
        }

        string _PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable PhoneNumber.
        /// </summary>
        [TestVariable("a5e74ee4-fd1e-400f-b65b-66afade5ce22")]
        public string PhoneNumber
        {
            get { return _PhoneNumber; }
            set { _PhoneNumber = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("bae04f83-d3b8-4d07-87e3-6511f83e2d35")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        string _Email;

        /// <summary>
        /// Gets or sets the value of variable Email.
        /// </summary>
        [TestVariable("8afd7366-b122-4ad8-b204-2c10e7084a37")]
        public string Email
        {
            get { return _Email; }
            set { _Email = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.ScanCardActivity.BtnNoCard' at Center", repo.PlusSparSi.ScanCardActivity.BtnNoCardInfo, new RecordItemIndex(0));
            repo.PlusSparSi.ScanCardActivity.BtnNoCard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterWelcomeActivity.BtnJoin' at Center", repo.PlusSparSi.RegisterWelcomeActivity.BtnJoinInfo, new RecordItemIndex(1));
            repo.PlusSparSi.RegisterWelcomeActivity.BtnJoin.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Name' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtName'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtNameInfo, new RecordItemIndex(2));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtName.Element.SetAttributeValue("Text", Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Surname' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtSurname'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtSurnameInfo, new RecordItemIndex(3));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtSurname.Element.SetAttributeValue("Text", Surname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$DateOfBirth' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirthInfo, new RecordItemIndex(4));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth.Element.SetAttributeValue("Text", DateOfBirth);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Gender' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtGender'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtGenderInfo, new RecordItemIndex(5));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtGender.Element.SetAttributeValue("Text", Gender);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep1PersonalDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep1PersonalDataActivity.BtnNextInfo, new RecordItemIndex(6));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Country' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountryInfo, new RecordItemIndex(7));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry.Element.SetAttributeValue("Text", Country);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Address' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreetInfo, new RecordItemIndex(8));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet.Element.SetAttributeValue("Text", Address);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$HouseNumber' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumber'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumberInfo, new RecordItemIndex(9));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumber.Element.SetAttributeValue("Text", HouseNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$PostalNumber' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtPostal'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtPostalInfo, new RecordItemIndex(10));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtPostal.Element.SetAttributeValue("Text", PostalNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$City' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCity'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCityInfo, new RecordItemIndex(11));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCity.Element.SetAttributeValue("Text", City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep2ResidentDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep2ResidentDataActivity.BtnNextInfo, new RecordItemIndex(12));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$PhoneNumber' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumber'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumberInfo, new RecordItemIndex(13));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumber.Element.SetAttributeValue("Text", PhoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'test' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtEmail'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo, new RecordItemIndex(14));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmail.Element.SetAttributeValue("Text", "test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPassword'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordInfo, new RecordItemIndex(15));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPassword.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeat'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeatInfo, new RecordItemIndex(16));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeat.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(17));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'test@' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtEmail'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo, new RecordItemIndex(18));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmail.Element.SetAttributeValue("Text", "test@");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(19));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'test@mailinator' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtEmail'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo, new RecordItemIndex(20));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmail.Element.SetAttributeValue("Text", "test@mailinator");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'testmailinator.com' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtEmail'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo, new RecordItemIndex(22));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmail.Element.SetAttributeValue("Text", "testmailinator.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '@mailinator.com' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtEmail'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo, new RecordItemIndex(24));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmail.Element.SetAttributeValue("Text", "@mailinator.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(25));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Set_Value_EtEmail(repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(27));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
