///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Step4_OptionalFieldsAdded recording.
    /// </summary>
    [TestModule("749c63db-6011-4a86-8400-91d30050ef1a", ModuleType.Recording, 1)]
    public partial class Step4_OptionalFieldsAdded : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Step4_OptionalFieldsAdded instance = new Step4_OptionalFieldsAdded();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Step4_OptionalFieldsAdded()
        {
            Name = "";
            Surname = "";
            DateOfBirth = "";
            Gender = "";
            Country = "";
            Address = "";
            HouseNumber = "";
            PostalNumber = "";
            City = "";
            PhoneNumber = "";
            Password = "";
            Email = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Step4_OptionalFieldsAdded Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("6c939326-6886-42a9-8344-4495138cdbd1")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        string _Surname;

        /// <summary>
        /// Gets or sets the value of variable Surname.
        /// </summary>
        [TestVariable("1eac8ff4-deb6-419b-b22e-7b093475a373")]
        public string Surname
        {
            get { return _Surname; }
            set { _Surname = value; }
        }

        string _DateOfBirth;

        /// <summary>
        /// Gets or sets the value of variable DateOfBirth.
        /// </summary>
        [TestVariable("05d129a8-70f5-4232-b0b7-5cf8ae256144")]
        public string DateOfBirth
        {
            get { return _DateOfBirth; }
            set { _DateOfBirth = value; }
        }

        string _Country;

        /// <summary>
        /// Gets or sets the value of variable Country.
        /// </summary>
        [TestVariable("7007e259-77fc-4438-aeeb-601afde2fbe5")]
        public string Country
        {
            get { return _Country; }
            set { _Country = value; }
        }

        string _Address;

        /// <summary>
        /// Gets or sets the value of variable Address.
        /// </summary>
        [TestVariable("faa113d9-21f2-4220-a1ad-9bd38014fdbb")]
        public string Address
        {
            get { return _Address; }
            set { _Address = value; }
        }

        string _HouseNumber;

        /// <summary>
        /// Gets or sets the value of variable HouseNumber.
        /// </summary>
        [TestVariable("4da6d0cd-94f6-4c18-9c6d-c2db4115c3cf")]
        public string HouseNumber
        {
            get { return _HouseNumber; }
            set { _HouseNumber = value; }
        }

        string _PostalNumber;

        /// <summary>
        /// Gets or sets the value of variable PostalNumber.
        /// </summary>
        [TestVariable("abd5b4e1-1976-4e42-97e0-cf8da5108c0f")]
        public string PostalNumber
        {
            get { return _PostalNumber; }
            set { _PostalNumber = value; }
        }

        string _City;

        /// <summary>
        /// Gets or sets the value of variable City.
        /// </summary>
        [TestVariable("70aed98a-5aad-443c-87c6-129422a5ebf3")]
        public string City
        {
            get { return _City; }
            set { _City = value; }
        }

        string _PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable PhoneNumber.
        /// </summary>
        [TestVariable("75d461c9-8afd-4d97-8266-72bb5d594e90")]
        public string PhoneNumber
        {
            get { return _PhoneNumber; }
            set { _PhoneNumber = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("48cc793e-558a-4e72-b11c-3baae9bc1b8d")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        string _Email;

        /// <summary>
        /// Gets or sets the value of variable Email.
        /// </summary>
        [TestVariable("9c52f78f-f802-499a-8be5-74ef4fd8af79")]
        public string Email
        {
            get { return _Email; }
            set { _Email = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("5fb77c63-2fd4-40a4-b114-d5ef2f28f673")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.ScanCardActivity.BtnNoCard' at Center", repo.PlusSparSi.ScanCardActivity.BtnNoCardInfo, new RecordItemIndex(0));
            repo.PlusSparSi.ScanCardActivity.BtnNoCard.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterWelcomeActivity.BtnJoin' at Center", repo.PlusSparSi.RegisterWelcomeActivity.BtnJoinInfo, new RecordItemIndex(1));
            repo.PlusSparSi.RegisterWelcomeActivity.BtnJoin.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Name' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtName'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtNameInfo, new RecordItemIndex(2));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtName.Element.SetAttributeValue("Text", Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Surname' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtSurname'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtSurnameInfo, new RecordItemIndex(3));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtSurname.Element.SetAttributeValue("Text", Surname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$DateOfBirth' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirthInfo, new RecordItemIndex(4));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtDateBirth.Element.SetAttributeValue("Text", DateOfBirth);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Gender' on item 'PlusSparSi.RegisterStep1PersonalDataActivity.EtGender'.", repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtGenderInfo, new RecordItemIndex(5));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.EtGender.Element.SetAttributeValue("Text", Gender);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep1PersonalDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep1PersonalDataActivity.BtnNextInfo, new RecordItemIndex(6));
            repo.PlusSparSi.RegisterStep1PersonalDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Country' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountryInfo, new RecordItemIndex(7));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCountry.Element.SetAttributeValue("Text", Country);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Address' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreetInfo, new RecordItemIndex(8));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtStreet.Element.SetAttributeValue("Text", Address);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$HouseNumber' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumber'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumberInfo, new RecordItemIndex(9));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtHouseNumber.Element.SetAttributeValue("Text", HouseNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$PostalNumber' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtPostal'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtPostalInfo, new RecordItemIndex(10));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtPostal.Element.SetAttributeValue("Text", PostalNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$City' on item 'PlusSparSi.RegisterStep2ResidentDataActivity.EtCity'.", repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCityInfo, new RecordItemIndex(11));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.EtCity.Element.SetAttributeValue("Text", City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep2ResidentDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep2ResidentDataActivity.BtnNextInfo, new RecordItemIndex(12));
            repo.PlusSparSi.RegisterStep2ResidentDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$PhoneNumber' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumber'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumberInfo, new RecordItemIndex(13));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPhoneNumber.Element.SetAttributeValue("Text", PhoneNumber);
            Delay.Milliseconds(0);
            
            Set_Value_EtEmail(repo.PlusSparSi.RegisterStep3AccountDataActivity.EtEmailInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPassword'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordInfo, new RecordItemIndex(16));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPassword.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$Password' on item 'PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeat'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeatInfo, new RecordItemIndex(17));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.EtPasswordRepeat.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext'.", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(18));
            Validate.Attribute(repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep3AccountDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNextInfo, new RecordItemIndex(19));
            repo.PlusSparSi.RegisterStep3AccountDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep4AdditionalDataActivity.SwDirectMail' at Center", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SwDirectMailInfo, new RecordItemIndex(20));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SwDirectMail.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep4AdditionalDataActivity.SwPhone' at Center", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SwPhoneInfo, new RecordItemIndex(21));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SwPhone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch Gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '.5' with swipe duration'500ms' and step count '0' on item 'PlusSparSi.RegisterStep4AdditionalDataActivity'.", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SelfInfo, new RecordItemIndex(22));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.Self.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", ".5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep4AdditionalDataActivity.TvEmail' at Center", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.TvEmailInfo, new RecordItemIndex(23));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.TvEmail.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterEmailNotificationsActivity.SwSparPlus' at Center", repo.PlusSparSi.RegisterEmailNotificationsActivity.SwSparPlusInfo, new RecordItemIndex(24));
            repo.PlusSparSi.RegisterEmailNotificationsActivity.SwSparPlus.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterEmailNotificationsActivity.NavigateUp' at Center", repo.PlusSparSi.RegisterEmailNotificationsActivity.NavigateUpInfo, new RecordItemIndex(25));
            repo.PlusSparSi.RegisterEmailNotificationsActivity.NavigateUp.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch Gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '.5' with swipe duration'500ms' and step count '0' on item 'PlusSparSi.RegisterStep4AdditionalDataActivity'.", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SelfInfo, new RecordItemIndex(26));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.Self.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", ".5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep4AdditionalDataActivity.SwSparApp' at Center", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SwSparAppInfo, new RecordItemIndex(27));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SwSparApp.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Yes' on item 'PlusSparSi.RegisterStep4AdditionalDataActivity.EtChildren'.", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.EtChildrenInfo, new RecordItemIndex(28));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.EtChildren.Element.SetAttributeValue("Text", "Yes");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '2' on item 'PlusSparSi.RegisterStep4AdditionalDataActivity.EtHouseholdNumber'.", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.EtHouseholdNumberInfo, new RecordItemIndex(29));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.EtHouseholdNumber.Element.SetAttributeValue("Text", "2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch Gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '.5' with swipe duration'500ms' and step count '0' on item 'PlusSparSi.RegisterStep4AdditionalDataActivity'.", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.SelfInfo, new RecordItemIndex(30));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.Self.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", ".5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.RegisterStep4AdditionalDataActivity.BtnNext' at Center", repo.PlusSparSi.RegisterStep4AdditionalDataActivity.BtnNextInfo, new RecordItemIndex(31));
            repo.PlusSparSi.RegisterStep4AdditionalDataActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Validate_LoginEmailSentActivity(repo.PlusSparSi.LoginEmailSentActivity.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.LoginEmailSentActivity.BtnEmailSentSkip' at Center", repo.PlusSparSi.LoginEmailSentActivity.BtnEmailSentSkipInfo, new RecordItemIndex(33));
            repo.PlusSparSi.LoginEmailSentActivity.BtnEmailSentSkip.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'PlusSparSi.OnBoardingStepOneActivity'.", repo.PlusSparSi.OnBoardingStepOneActivity.SelfInfo, new RecordItemIndex(34));
            Validate.Attribute(repo.PlusSparSi.OnBoardingStepOneActivity.SelfInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
