///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Utility
{
    public partial class ClearAppData
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ClearData()
        {
            string pathToAdb      = "C:\\ADB\\adb.exe";                  //your path to adb.exe goes here
			string appPackageName = "plus.spar.si";   //the packagename of your app
			
			Process adbClearProcess = new Process();
			adbClearProcess.StartInfo.FileName  = pathToAdb;
			adbClearProcess.StartInfo.Arguments = string.Format("shell rm -r /data/data/{0}/", appPackageName);
			adbClearProcess.Start();
			
			adbClearProcess.WaitForExit();
			
			Process adbCreateDirProcess = new Process();
			adbCreateDirProcess.StartInfo.FileName  = pathToAdb;
			adbCreateDirProcess.StartInfo.Arguments = string.Format("shell mkdir /data/data/{0}/", appPackageName);
			adbCreateDirProcess.Start();
			
			adbCreateDirProcess.WaitForExit();
        }

    }
}
