///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Remoting;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Utility
{
    public partial class ClearAppData
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
                
        public void ClearData()
        {            
            string pathToAdb      = "C:\\Program Files (x86)\\Ranorex 6.2\\Bin\\RxEnv\\Android\\tools\\adb.exe";         //your path to adb.exe goes here
			string appPackageName = PackageName;  																		 //the packagename of your app
			
			var device = RemoteServiceLocator.Service.GetByDisplayName(DeviceName);
			int port = device.Port;
			string host = device.Host;
			Report.Log(ReportLevel.Info, "Device: " + device.ToString() + "Port: " + port + ", Host: " + host, "");
			
			Process adbCreateDirProcess = new Process();
			adbCreateDirProcess.StartInfo.FileName  = pathToAdb;
			adbCreateDirProcess.StartInfo.Arguments = string.Format("adb tcpip {0}", port);
			adbCreateDirProcess.Start();
			adbCreateDirProcess.WaitForExit();
			
			adbCreateDirProcess = new Process();
			adbCreateDirProcess.StartInfo.FileName  = pathToAdb;
			adbCreateDirProcess.StartInfo.Arguments = string.Format("adb connect {0}", host);
			adbCreateDirProcess.Start();
			adbCreateDirProcess.WaitForExit();
			
			adbCreateDirProcess = new Process();
			adbCreateDirProcess.StartInfo.FileName  = pathToAdb;
			adbCreateDirProcess.StartInfo.Arguments = string.Format("adb shell pm clear {0}", appPackageName);
			adbCreateDirProcess.Start();			
			adbCreateDirProcess.WaitForExit();
			
			var app = device.RanorexCompatibleApps[0]; 
			device.StartApplication(app);
			
        }
    }
}
