///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Utility
{
    public partial class Permissions_DenyCameraAccess
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void DenyCameraPermission()
        {
            string appPackageName = PackageName;
			string pathToAdb = "C:\\Program Files (x86)\\Ranorex 6.2\\Bin\\RxEnv\\Android\\tools\\adb.exe";
						
			Process adbClearProcess = new Process();
			adbClearProcess.StartInfo.FileName  = pathToAdb;
			adbClearProcess.StartInfo.Arguments = string.Format("shell pm revoke {0} android.permission.CAMERA", appPackageName);
			adbClearProcess.Start();
			
			adbClearProcess.WaitForExit();
        }

    }
}
