///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Utility
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RunApp recording.
    /// </summary>
    [TestModule("47c4d39f-0d71-4abc-bcb7-f146aaa7813a", ModuleType.Recording, 1)]
    public partial class RunApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static RunApp instance = new RunApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RunApp()
        {
            DeviceName = "";
            PackageName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RunApp Instance
        {
            get { return instance; }
        }

#region Variables

        string _DeviceName;

        /// <summary>
        /// Gets or sets the value of variable DeviceName.
        /// </summary>
        [TestVariable("7ba94856-ce36-433b-aa83-673fcd1b06d7")]
        public string DeviceName
        {
            get { return _DeviceName; }
            set { _DeviceName = value; }
        }

        string _PackageName;

        /// <summary>
        /// Gets or sets the value of variable PackageName.
        /// </summary>
        [TestVariable("4de25083-df64-42d6-97dd-017c0a227675")]
        public string PackageName
        {
            get { return _PackageName; }
            set { _PackageName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app from variable $PackageName on device from variable $DeviceName.", new RecordItemIndex(0));
            Host.Local.RunMobileApp(DeviceName, PackageName, true);
            Delay.Milliseconds(3500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
