///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar.Test_cases.Landing
{
	public partial class SparKlub_Open
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}
		
		public void OpenSparKlub(){
			
			int tryNum = 0;
			bool exists = false;
			
			while(tryNum < 6 && !exists){
				
				tryNum++;
				repo.PlusSparSi.SearchTimeout = new Duration(1500);
				repo.PlusSparSi.MainActivity.SearchTimeout = new Duration(1500);
				repo.PlusSparSi.MainActivity.TvSparPlusKlubInfo.SearchTimeout = new Duration(1000);
				
				exists = repo.PlusSparSi.MainActivity.TvSparPlusKlubInfo.Exists();
				
				if(!exists){
					Report.Log(ReportLevel.Info, "Info", "TryNum: " + tryNum);
					repo.PlusSparSi.MainActivity.Self.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "0.5"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
					Delay.Milliseconds(500);
				}else
					break;
			}
			
			if(exists){
				Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.ImgJedelBi' at Center", repo.PlusSparSi.MainActivity.ImgJedelBiInfo, new RecordItemIndex(4));
				repo.PlusSparSi.MainActivity.TvSparPlusKlub.Touch();
				Delay.Milliseconds(500);
			}
		}
	}
}
