///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar_iOS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Spar_iOSRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("65ea51bf-c99f-4718-a7e5-ad52ba5e81eb")]
    public partial class Spar_iOSRepository : RepoGenBaseFolder
    {
        static Spar_iOSRepository instance = new Spar_iOSRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Spar_iOSRepository element repository.
        /// </summary>
        [RepositoryFolder("65ea51bf-c99f-4718-a7e5-ad52ba5e81eb")]
        public static Spar_iOSRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Spar_iOSRepository() 
            : base("Spar_iOSRepository", "/", null, 0, false, "65ea51bf-c99f-4718-a7e5-ad52ba5e81eb", ".\\RepositoryImages\\Spar_iOSRepository65ea51bf.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("65ea51bf-c99f-4718-a7e5-ad52ba5e81eb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class Spar_iOSRepositoryFolders
    {
    }
#pragma warning restore 0436
}