///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace iOS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the iOSRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("e05032cf-d1a7-4690-9c66-a34a55e467a5")]
    public partial class iOSRepository : RepoGenBaseFolder
    {
        static iOSRepository instance = new iOSRepository();

        /// <summary>
        /// Gets the singleton class instance representing the iOSRepository element repository.
        /// </summary>
        [RepositoryFolder("e05032cf-d1a7-4690-9c66-a34a55e467a5")]
        public static iOSRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public iOSRepository() 
            : base("iOSRepository", "/", null, 0, false, "e05032cf-d1a7-4690-9c66-a34a55e467a5", ".\\RepositoryImages\\iOSRepositorye05032cf.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e05032cf-d1a7-4690-9c66-a34a55e467a5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class iOSRepositoryFolders
    {
    }
#pragma warning restore 0436
}