///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Landing.Locations
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Location_PermissionDenied_OpenLocationDetails recording.
    /// </summary>
    [TestModule("f8876515-4b7f-418d-ab6c-fc63fb228a31", ModuleType.Recording, 1)]
    public partial class Location_PermissionDenied_OpenLocationDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Location_PermissionDenied_OpenLocationDetails instance = new Location_PermissionDenied_OpenLocationDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Location_PermissionDenied_OpenLocationDetails()
        {
            StoreTitle = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Location_PermissionDenied_OpenLocationDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _StoreTitle;

        /// <summary>
        /// Gets or sets the value of variable StoreTitle.
        /// </summary>
        [TestVariable("5e6eb797-9665-457a-b110-89e61feb0cf4")]
        public string StoreTitle
        {
            get { return _StoreTitle; }
            set { _StoreTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            FindFirstLocation();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
