///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Boarding
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterSerialNumberManually recording.
    /// </summary>
    [TestModule("26753f43-843f-4900-b108-34c6c6376398", ModuleType.Recording, 1)]
    public partial class EnterSerialNumberManually : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static EnterSerialNumberManually instance = new EnterSerialNumberManually();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterSerialNumberManually()
        {
            SerialNumber = "12345678";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterSerialNumberManually Instance
        {
            get { return instance; }
        }

#region Variables

        string _SerialNumber;

        /// <summary>
        /// Gets or sets the value of variable SerialNumber.
        /// </summary>
        [TestVariable("136c7f21-6d80-49cd-b9c6-deb114bd0d19")]
        public string SerialNumber
        {
            get { return _SerialNumber; }
            set { _SerialNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.ScanCardActivity.BtnManualInsertCardNumber' at Center", repo.PlusSparSi.ScanCardActivity.BtnManualInsertCardNumberInfo, new RecordItemIndex(0));
            repo.PlusSparSi.ScanCardActivity.BtnManualInsertCardNumber.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Enter card serial number') on item 'PlusSparSi.EnterNumberActivity.RStringScancardEnterCardNumber'.", repo.PlusSparSi.EnterNumberActivity.RStringScancardEnterCardNumberInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.PlusSparSi.EnterNumberActivity.RStringScancardEnterCardNumberInfo, "Text", "Enter card serial number");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'PlusSparSi.EnterNumberActivity.BtnNext'.", repo.PlusSparSi.EnterNumberActivity.BtnNextInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.PlusSparSi.EnterNumberActivity.BtnNextInfo, "Enabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$SerialNumber' on item 'PlusSparSi.EnterNumberActivity.EtCardNumber'.", repo.PlusSparSi.EnterNumberActivity.EtCardNumberInfo, new RecordItemIndex(3));
            repo.PlusSparSi.EnterNumberActivity.EtCardNumber.Element.SetAttributeValue("Text", SerialNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'PlusSparSi.EnterNumberActivity.BtnNext'.", repo.PlusSparSi.EnterNumberActivity.BtnNextInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.PlusSparSi.EnterNumberActivity.BtnNextInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
