///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Boarding
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Scan recording.
    /// </summary>
    [TestModule("894881bf-77b0-4001-881f-968ef7c36016", ModuleType.Recording, 1)]
    public partial class Scan : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static Scan instance = new Scan();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Scan()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Scan Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.ScanCardActivity.BtnScan' at Center", repo.PlusSparSi.ScanCardActivity.BtnScanInfo, new RecordItemIndex(0));
            repo.PlusSparSi.ScanCardActivity.BtnScan.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Scan EAN code') on item 'PlusSparSi.BarCodeScannerActivity.RStringBarCodeScannerActionbarTitl'.", repo.PlusSparSi.BarCodeScannerActivity.RStringBarCodeScannerActionbarTitlInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.PlusSparSi.BarCodeScannerActivity.RStringBarCodeScannerActionbarTitlInfo, "Text", "Scan EAN code");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.BarCodeScannerActivity.NavigateUp' at Center", repo.PlusSparSi.BarCodeScannerActivity.NavigateUpInfo, new RecordItemIndex(2));
            repo.PlusSparSi.BarCodeScannerActivity.NavigateUp.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.ScanCardActivity'.", repo.PlusSparSi.ScanCardActivity.SelfInfo, new RecordItemIndex(3));
            Validate.Exists(repo.PlusSparSi.ScanCardActivity.SelfInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
