///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Spar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SparRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("c12fa4a9-bf96-41a7-9866-79edafaddcf2")]
    public partial class SparRepository : RepoGenBaseFolder
    {
        static SparRepository instance = new SparRepository();
        SparRepositoryFolders.PlusSparSiAppFolder _plussparsi;

        /// <summary>
        /// Gets the singleton class instance representing the SparRepository element repository.
        /// </summary>
        [RepositoryFolder("c12fa4a9-bf96-41a7-9866-79edafaddcf2")]
        public static SparRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SparRepository() 
            : base("SparRepository", "/", null, 0, false, "c12fa4a9-bf96-41a7-9866-79edafaddcf2", ".\\RepositoryImages\\SparRepositoryc12fa4a9.rximgres")
        {
            _plussparsi = new SparRepositoryFolders.PlusSparSiAppFolder(this);
        }

#region Variables

        string _PackageName = "plus.spar.si";

        /// <summary>
        /// Gets or sets the value of variable PackageName.
        /// </summary>
        [TestVariable("34011a8a-5d5e-4397-86a8-f0ab4048e5d0")]
        public string PackageName
        {
            get { return _PackageName; }
            set { _PackageName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c12fa4a9-bf96-41a7-9866-79edafaddcf2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PlusSparSi folder.
        /// </summary>
        [RepositoryFolder("f885d0cd-d406-48ca-a29d-75d836c2cf92")]
        public virtual SparRepositoryFolders.PlusSparSiAppFolder PlusSparSi
        {
            get { return _plussparsi; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class SparRepositoryFolders
    {
        /// <summary>
        /// The PlusSparSiAppFolder folder.
        /// </summary>
        [RepositoryFolder("f885d0cd-d406-48ca-a29d-75d836c2cf92")]
        public partial class PlusSparSiAppFolder : RepoGenBaseFolder
        {
            SparRepositoryFolders.ScanCardActivityFolder _scancardactivity;
            SparRepositoryFolders.RegisterWelcomeActivityFolder _registerwelcomeactivity;
            SparRepositoryFolders.RegisterStep1PersonalDataActivityFolder _registerstep1personaldataactivity;
            SparRepositoryFolders.BarCodeScannerActivityFolder _barcodescanneractivity;
            SparRepositoryFolders.OnBoardingStepOneActivityFolder _onboardingsteponeactivity;
            SparRepositoryFolders.OnBoardingStepTwoActivityFolder _onboardingsteptwoactivity;
            SparRepositoryFolders.OnBoardingStepThreeActivityFolder _onboardingstepthreeactivity;
            SparRepositoryFolders.MainActivityFolder _mainactivity;
            SparRepositoryFolders.EnterNumberActivityFolder _enternumberactivity;
            SparRepositoryFolders.ScanCardTermsAndConditionsFolder _scancardtermsandconditions;
            SparRepositoryFolders.RegisterStep2ResidentDataActivityFolder _registerstep2residentdataactivity;
            SparRepositoryFolders.RegisterStep3AccountDataActivityFolder _registerstep3accountdataactivity;
            SparRepositoryFolders.RegisterStep4AdditionalDataActivityFolder _registerstep4additionaldataactivity;
            SparRepositoryFolders.LoginEmailSentActivityFolder _loginemailsentactivity;

            /// <summary>
            /// Creates a new PlusSparSi  folder.
            /// </summary>
            public PlusSparSiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PlusSparSi", "/mobileapp[@title='plus.spar.si.staging']", parentFolder, 30000, null, false, "f885d0cd-d406-48ca-a29d-75d836c2cf92", "")
            {
                _scancardactivity = new SparRepositoryFolders.ScanCardActivityFolder(this);
                _registerwelcomeactivity = new SparRepositoryFolders.RegisterWelcomeActivityFolder(this);
                _registerstep1personaldataactivity = new SparRepositoryFolders.RegisterStep1PersonalDataActivityFolder(this);
                _barcodescanneractivity = new SparRepositoryFolders.BarCodeScannerActivityFolder(this);
                _onboardingsteponeactivity = new SparRepositoryFolders.OnBoardingStepOneActivityFolder(this);
                _onboardingsteptwoactivity = new SparRepositoryFolders.OnBoardingStepTwoActivityFolder(this);
                _onboardingstepthreeactivity = new SparRepositoryFolders.OnBoardingStepThreeActivityFolder(this);
                _mainactivity = new SparRepositoryFolders.MainActivityFolder(this);
                _enternumberactivity = new SparRepositoryFolders.EnterNumberActivityFolder(this);
                _scancardtermsandconditions = new SparRepositoryFolders.ScanCardTermsAndConditionsFolder(this);
                _registerstep2residentdataactivity = new SparRepositoryFolders.RegisterStep2ResidentDataActivityFolder(this);
                _registerstep3accountdataactivity = new SparRepositoryFolders.RegisterStep3AccountDataActivityFolder(this);
                _registerstep4additionaldataactivity = new SparRepositoryFolders.RegisterStep4AdditionalDataActivityFolder(this);
                _loginemailsentactivity = new SparRepositoryFolders.LoginEmailSentActivityFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f885d0cd-d406-48ca-a29d-75d836c2cf92")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f885d0cd-d406-48ca-a29d-75d836c2cf92")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ScanCardActivity folder.
            /// </summary>
            [RepositoryFolder("34dbf98f-9c14-4923-add2-96dcad5eac90")]
            public virtual SparRepositoryFolders.ScanCardActivityFolder ScanCardActivity
            {
                get { return _scancardactivity; }
            }

            /// <summary>
            /// The RegisterWelcomeActivity folder.
            /// </summary>
            [RepositoryFolder("56ec5b6a-6b8f-40de-8f5e-eb64a41ab44c")]
            public virtual SparRepositoryFolders.RegisterWelcomeActivityFolder RegisterWelcomeActivity
            {
                get { return _registerwelcomeactivity; }
            }

            /// <summary>
            /// The RegisterStep1PersonalDataActivity folder.
            /// </summary>
            [RepositoryFolder("5eacb6a6-7012-4813-8cbb-3c4fb7f3625c")]
            public virtual SparRepositoryFolders.RegisterStep1PersonalDataActivityFolder RegisterStep1PersonalDataActivity
            {
                get { return _registerstep1personaldataactivity; }
            }

            /// <summary>
            /// The BarCodeScannerActivity folder.
            /// </summary>
            [RepositoryFolder("311e2466-032e-4bec-9cd0-5d971b904122")]
            public virtual SparRepositoryFolders.BarCodeScannerActivityFolder BarCodeScannerActivity
            {
                get { return _barcodescanneractivity; }
            }

            /// <summary>
            /// The OnBoardingStepOneActivity folder.
            /// </summary>
            [RepositoryFolder("e5288b06-59df-4612-b679-57269effd9b3")]
            public virtual SparRepositoryFolders.OnBoardingStepOneActivityFolder OnBoardingStepOneActivity
            {
                get { return _onboardingsteponeactivity; }
            }

            /// <summary>
            /// The OnBoardingStepTwoActivity folder.
            /// </summary>
            [RepositoryFolder("9250a1cd-c071-4670-adfc-369fad748a97")]
            public virtual SparRepositoryFolders.OnBoardingStepTwoActivityFolder OnBoardingStepTwoActivity
            {
                get { return _onboardingsteptwoactivity; }
            }

            /// <summary>
            /// The OnBoardingStepThreeActivity folder.
            /// </summary>
            [RepositoryFolder("b68303be-b644-4ef1-ad0a-2ddcfc6d5b9f")]
            public virtual SparRepositoryFolders.OnBoardingStepThreeActivityFolder OnBoardingStepThreeActivity
            {
                get { return _onboardingstepthreeactivity; }
            }

            /// <summary>
            /// The MainActivity folder.
            /// </summary>
            [RepositoryFolder("04550d2f-0065-4f16-a9d6-1d6d447f1a0a")]
            public virtual SparRepositoryFolders.MainActivityFolder MainActivity
            {
                get { return _mainactivity; }
            }

            /// <summary>
            /// The EnterNumberActivity folder.
            /// </summary>
            [RepositoryFolder("42a91c57-ca33-40f3-9bc1-078ca11dc89e")]
            public virtual SparRepositoryFolders.EnterNumberActivityFolder EnterNumberActivity
            {
                get { return _enternumberactivity; }
            }

            /// <summary>
            /// The ScanCardTermsAndConditions folder.
            /// </summary>
            [RepositoryFolder("03197287-5ad7-4b1f-b779-9b6fb51b7276")]
            public virtual SparRepositoryFolders.ScanCardTermsAndConditionsFolder ScanCardTermsAndConditions
            {
                get { return _scancardtermsandconditions; }
            }

            /// <summary>
            /// The RegisterStep2ResidentDataActivity folder.
            /// </summary>
            [RepositoryFolder("2a0e1471-e669-4ec1-a303-48ca12e9a275")]
            public virtual SparRepositoryFolders.RegisterStep2ResidentDataActivityFolder RegisterStep2ResidentDataActivity
            {
                get { return _registerstep2residentdataactivity; }
            }

            /// <summary>
            /// The RegisterStep3AccountDataActivity folder.
            /// </summary>
            [RepositoryFolder("8c2ab8b0-4adc-4325-a95e-ad97720e7c5b")]
            public virtual SparRepositoryFolders.RegisterStep3AccountDataActivityFolder RegisterStep3AccountDataActivity
            {
                get { return _registerstep3accountdataactivity; }
            }

            /// <summary>
            /// The RegisterStep4AdditionalDataActivity folder.
            /// </summary>
            [RepositoryFolder("8625c355-2d72-4d5a-819d-ef0b52abe409")]
            public virtual SparRepositoryFolders.RegisterStep4AdditionalDataActivityFolder RegisterStep4AdditionalDataActivity
            {
                get { return _registerstep4additionaldataactivity; }
            }

            /// <summary>
            /// The LoginEmailSentActivity folder.
            /// </summary>
            [RepositoryFolder("138292e3-349e-40be-ad83-efa673a0e21f")]
            public virtual SparRepositoryFolders.LoginEmailSentActivityFolder LoginEmailSentActivity
            {
                get { return _loginemailsentactivity; }
            }
        }

        /// <summary>
        /// The ScanCardActivityFolder folder.
        /// </summary>
        [RepositoryFolder("34dbf98f-9c14-4923-add2-96dcad5eac90")]
        public partial class ScanCardActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startscanningtitleInfo;
            RepoItemInfo _btnscanInfo;
            RepoItemInfo _btnnocardInfo;
            RepoItemInfo _btnmanualinsertcardnumberInfo;
            RepoItemInfo _termsInfo;

            /// <summary>
            /// Creates a new ScanCardActivity  folder.
            /// </summary>
            public ScanCardActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("ScanCardActivity", "form[@title='ScanCardActivity']", parentFolder, 30000, null, false, "34dbf98f-9c14-4923-add2-96dcad5eac90", "")
            {
                _startscanningtitleInfo = new RepoItemInfo(this, "StartScanningTitle", ".//text[@resourceid='R.string.scancard_info_title']", 30000, null, "98bbe845-d99b-4151-8a22-9689ba200472");
                _btnscanInfo = new RepoItemInfo(this, "BtnScan", ".//text[@rid='btn_scan']", 30000, null, "83b6c29f-59b7-436c-9da7-1d8811331049");
                _btnnocardInfo = new RepoItemInfo(this, "BtnNoCard", ".//text[@rid='btn_no_card']", 30000, null, "255de8dd-ff61-4d9f-b4cf-4d5b4ffca6c8");
                _btnmanualinsertcardnumberInfo = new RepoItemInfo(this, "BtnManualInsertCardNumber", ".//text[@rid='btn_manual_insert_card_number']", 30000, null, "9197c359-ff23-472b-b9fb-50a4e980793a");
                _termsInfo = new RepoItemInfo(this, "Terms", ".//text[@rid='tv_footer_terms']", 30000, null, "653dbf57-0a57-4e00-8088-265dfefa91e3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34dbf98f-9c14-4923-add2-96dcad5eac90")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34dbf98f-9c14-4923-add2-96dcad5eac90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The StartScanningTitle item.
            /// </summary>
            [RepositoryItem("98bbe845-d99b-4151-8a22-9689ba200472")]
            public virtual Ranorex.Text StartScanningTitle
            {
                get
                {
                    return _startscanningtitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StartScanningTitle item info.
            /// </summary>
            [RepositoryItemInfo("98bbe845-d99b-4151-8a22-9689ba200472")]
            public virtual RepoItemInfo StartScanningTitleInfo
            {
                get
                {
                    return _startscanningtitleInfo;
                }
            }

            /// <summary>
            /// The BtnScan item.
            /// </summary>
            [RepositoryItem("83b6c29f-59b7-436c-9da7-1d8811331049")]
            public virtual Ranorex.Text BtnScan
            {
                get
                {
                    return _btnscanInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnScan item info.
            /// </summary>
            [RepositoryItemInfo("83b6c29f-59b7-436c-9da7-1d8811331049")]
            public virtual RepoItemInfo BtnScanInfo
            {
                get
                {
                    return _btnscanInfo;
                }
            }

            /// <summary>
            /// The BtnNoCard item.
            /// </summary>
            [RepositoryItem("255de8dd-ff61-4d9f-b4cf-4d5b4ffca6c8")]
            public virtual Ranorex.Text BtnNoCard
            {
                get
                {
                    return _btnnocardInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnNoCard item info.
            /// </summary>
            [RepositoryItemInfo("255de8dd-ff61-4d9f-b4cf-4d5b4ffca6c8")]
            public virtual RepoItemInfo BtnNoCardInfo
            {
                get
                {
                    return _btnnocardInfo;
                }
            }

            /// <summary>
            /// The BtnManualInsertCardNumber item.
            /// </summary>
            [RepositoryItem("9197c359-ff23-472b-b9fb-50a4e980793a")]
            public virtual Ranorex.Text BtnManualInsertCardNumber
            {
                get
                {
                    return _btnmanualinsertcardnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnManualInsertCardNumber item info.
            /// </summary>
            [RepositoryItemInfo("9197c359-ff23-472b-b9fb-50a4e980793a")]
            public virtual RepoItemInfo BtnManualInsertCardNumberInfo
            {
                get
                {
                    return _btnmanualinsertcardnumberInfo;
                }
            }

            /// <summary>
            /// The Terms item.
            /// </summary>
            [RepositoryItem("653dbf57-0a57-4e00-8088-265dfefa91e3")]
            public virtual Ranorex.Text Terms
            {
                get
                {
                    return _termsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Terms item info.
            /// </summary>
            [RepositoryItemInfo("653dbf57-0a57-4e00-8088-265dfefa91e3")]
            public virtual RepoItemInfo TermsInfo
            {
                get
                {
                    return _termsInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterWelcomeActivityFolder folder.
        /// </summary>
        [RepositoryFolder("56ec5b6a-6b8f-40de-8f5e-eb64a41ab44c")]
        public partial class RegisterWelcomeActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _registerwelcomeinfotitleInfo;
            RepoItemInfo _registerwelcomeexclusiveInfo;
            RepoItemInfo _registerwelcomecollectingcreInfo;
            RepoItemInfo _registerwelcomecardaccessInfo;
            RepoItemInfo _btnjoinInfo;
            RepoItemInfo _btnskipInfo;

            /// <summary>
            /// Creates a new RegisterWelcomeActivity  folder.
            /// </summary>
            public RegisterWelcomeActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterWelcomeActivity", "form[@title='RegisterWelcomeActivity']", parentFolder, 30000, null, false, "56ec5b6a-6b8f-40de-8f5e-eb64a41ab44c", "")
            {
                _registerwelcomeinfotitleInfo = new RepoItemInfo(this, "RegisterWelcomeInfoTitle", ".//text[@resourceid='R.string.register_welcome_info_title']", 30000, null, "ccf96f7e-be42-417e-a9d3-d4fed0d57bd4");
                _registerwelcomeexclusiveInfo = new RepoItemInfo(this, "RegisterWelcomeExclusive", ".//text[@resourceid='R.string.register_welcome_exclusive']", 30000, null, "4917a2ec-8ef3-4c6e-ab8b-b44b109a5259");
                _registerwelcomecollectingcreInfo = new RepoItemInfo(this, "RegisterWelcomeCollectingCre", ".//text[@resourceid='R.string.register_welcome_collecting_credit']", 30000, null, "5d9adda4-730f-4802-b5d8-4544b3c1056b");
                _registerwelcomecardaccessInfo = new RepoItemInfo(this, "RegisterWelcomeCardAccess", ".//text[@resourceid='R.string.register_welcome_card_access']", 30000, null, "e8353065-e159-4ffd-ad3e-cf97b1c4a7fc");
                _btnjoinInfo = new RepoItemInfo(this, "BtnJoin", ".//text[@rid='btn_join']", 30000, null, "5caae247-565b-40a6-b4c3-c709d62634fe");
                _btnskipInfo = new RepoItemInfo(this, "BtnSkip", ".//text[@rid='btn_skip']", 30000, null, "f4686bcf-7100-4d8d-9551-6a8db3a0f7d2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("56ec5b6a-6b8f-40de-8f5e-eb64a41ab44c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("56ec5b6a-6b8f-40de-8f5e-eb64a41ab44c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RegisterWelcomeInfoTitle item.
            /// </summary>
            [RepositoryItem("ccf96f7e-be42-417e-a9d3-d4fed0d57bd4")]
            public virtual Ranorex.Text RegisterWelcomeInfoTitle
            {
                get
                {
                    return _registerwelcomeinfotitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RegisterWelcomeInfoTitle item info.
            /// </summary>
            [RepositoryItemInfo("ccf96f7e-be42-417e-a9d3-d4fed0d57bd4")]
            public virtual RepoItemInfo RegisterWelcomeInfoTitleInfo
            {
                get
                {
                    return _registerwelcomeinfotitleInfo;
                }
            }

            /// <summary>
            /// The RegisterWelcomeExclusive item.
            /// </summary>
            [RepositoryItem("4917a2ec-8ef3-4c6e-ab8b-b44b109a5259")]
            public virtual Ranorex.Text RegisterWelcomeExclusive
            {
                get
                {
                    return _registerwelcomeexclusiveInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RegisterWelcomeExclusive item info.
            /// </summary>
            [RepositoryItemInfo("4917a2ec-8ef3-4c6e-ab8b-b44b109a5259")]
            public virtual RepoItemInfo RegisterWelcomeExclusiveInfo
            {
                get
                {
                    return _registerwelcomeexclusiveInfo;
                }
            }

            /// <summary>
            /// The RegisterWelcomeCollectingCre item.
            /// </summary>
            [RepositoryItem("5d9adda4-730f-4802-b5d8-4544b3c1056b")]
            public virtual Ranorex.Text RegisterWelcomeCollectingCre
            {
                get
                {
                    return _registerwelcomecollectingcreInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RegisterWelcomeCollectingCre item info.
            /// </summary>
            [RepositoryItemInfo("5d9adda4-730f-4802-b5d8-4544b3c1056b")]
            public virtual RepoItemInfo RegisterWelcomeCollectingCreInfo
            {
                get
                {
                    return _registerwelcomecollectingcreInfo;
                }
            }

            /// <summary>
            /// The RegisterWelcomeCardAccess item.
            /// </summary>
            [RepositoryItem("e8353065-e159-4ffd-ad3e-cf97b1c4a7fc")]
            public virtual Ranorex.Text RegisterWelcomeCardAccess
            {
                get
                {
                    return _registerwelcomecardaccessInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RegisterWelcomeCardAccess item info.
            /// </summary>
            [RepositoryItemInfo("e8353065-e159-4ffd-ad3e-cf97b1c4a7fc")]
            public virtual RepoItemInfo RegisterWelcomeCardAccessInfo
            {
                get
                {
                    return _registerwelcomecardaccessInfo;
                }
            }

            /// <summary>
            /// The BtnJoin item.
            /// </summary>
            [RepositoryItem("5caae247-565b-40a6-b4c3-c709d62634fe")]
            public virtual Ranorex.Text BtnJoin
            {
                get
                {
                    return _btnjoinInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnJoin item info.
            /// </summary>
            [RepositoryItemInfo("5caae247-565b-40a6-b4c3-c709d62634fe")]
            public virtual RepoItemInfo BtnJoinInfo
            {
                get
                {
                    return _btnjoinInfo;
                }
            }

            /// <summary>
            /// The BtnSkip item.
            /// </summary>
            [RepositoryItem("f4686bcf-7100-4d8d-9551-6a8db3a0f7d2")]
            public virtual Ranorex.Text BtnSkip
            {
                get
                {
                    return _btnskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnSkip item info.
            /// </summary>
            [RepositoryItemInfo("f4686bcf-7100-4d8d-9551-6a8db3a0f7d2")]
            public virtual RepoItemInfo BtnSkipInfo
            {
                get
                {
                    return _btnskipInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterStep1PersonalDataActivityFolder folder.
        /// </summary>
        [RepositoryFolder("5eacb6a6-7012-4813-8cbb-3c4fb7f3625c")]
        public partial class RegisterStep1PersonalDataActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _registerpersonalinfotitleInfo;
            RepoItemInfo _etnameInfo;
            RepoItemInfo _etsurnameInfo;
            RepoItemInfo _etdatebirthInfo;
            RepoItemInfo _etgenderInfo;
            RepoItemInfo _btnnextInfo;
            RepoItemInfo _btnskipInfo;

            /// <summary>
            /// Creates a new RegisterStep1PersonalDataActivity  folder.
            /// </summary>
            public RegisterStep1PersonalDataActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterStep1PersonalDataActivity", "form[@title~'^RegisterStep1PersonalData']", parentFolder, 30000, null, false, "5eacb6a6-7012-4813-8cbb-3c4fb7f3625c", "")
            {
                _registerpersonalinfotitleInfo = new RepoItemInfo(this, "RegisterPersonalInfoTitle", ".//text[@resourceid='R.string.register_personal_info_title']", 30000, null, "d80a8e96-dd8f-4152-addc-368098ee47a6");
                _etnameInfo = new RepoItemInfo(this, "EtName", ".//text[@rid='et_name']", 30000, null, "3dd0d887-0311-4138-92a4-11ebd7eda214");
                _etsurnameInfo = new RepoItemInfo(this, "EtSurname", ".//text[@rid='et_surname']", 30000, null, "01d66e75-b102-4736-b944-56bb068142e1");
                _etdatebirthInfo = new RepoItemInfo(this, "EtDateBirth", ".//text[@rid='et_date_birth']", 30000, null, "117ddf31-b790-479f-a752-77c4ab4867ce");
                _etgenderInfo = new RepoItemInfo(this, "EtGender", ".//text[@rid='et_gender']", 30000, null, "68d14a1e-ded3-40e6-83b1-bbda76c9da82");
                _btnnextInfo = new RepoItemInfo(this, "BtnNext", ".//text[@rid='btn_next']", 30000, null, "7b133682-4665-4f25-989e-1bf1b36453f6");
                _btnskipInfo = new RepoItemInfo(this, "BtnSkip", ".//text[@rid='btn_skip']", 30000, null, "a846c0ca-ad31-4dd6-a433-68af9d2a5513");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5eacb6a6-7012-4813-8cbb-3c4fb7f3625c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5eacb6a6-7012-4813-8cbb-3c4fb7f3625c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RegisterPersonalInfoTitle item.
            /// </summary>
            [RepositoryItem("d80a8e96-dd8f-4152-addc-368098ee47a6")]
            public virtual Ranorex.Text RegisterPersonalInfoTitle
            {
                get
                {
                    return _registerpersonalinfotitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RegisterPersonalInfoTitle item info.
            /// </summary>
            [RepositoryItemInfo("d80a8e96-dd8f-4152-addc-368098ee47a6")]
            public virtual RepoItemInfo RegisterPersonalInfoTitleInfo
            {
                get
                {
                    return _registerpersonalinfotitleInfo;
                }
            }

            /// <summary>
            /// The EtName item.
            /// </summary>
            [RepositoryItem("3dd0d887-0311-4138-92a4-11ebd7eda214")]
            public virtual Ranorex.Text EtName
            {
                get
                {
                    return _etnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtName item info.
            /// </summary>
            [RepositoryItemInfo("3dd0d887-0311-4138-92a4-11ebd7eda214")]
            public virtual RepoItemInfo EtNameInfo
            {
                get
                {
                    return _etnameInfo;
                }
            }

            /// <summary>
            /// The EtSurname item.
            /// </summary>
            [RepositoryItem("01d66e75-b102-4736-b944-56bb068142e1")]
            public virtual Ranorex.Text EtSurname
            {
                get
                {
                    return _etsurnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtSurname item info.
            /// </summary>
            [RepositoryItemInfo("01d66e75-b102-4736-b944-56bb068142e1")]
            public virtual RepoItemInfo EtSurnameInfo
            {
                get
                {
                    return _etsurnameInfo;
                }
            }

            /// <summary>
            /// The EtDateBirth item.
            /// </summary>
            [RepositoryItem("117ddf31-b790-479f-a752-77c4ab4867ce")]
            public virtual Ranorex.Text EtDateBirth
            {
                get
                {
                    return _etdatebirthInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtDateBirth item info.
            /// </summary>
            [RepositoryItemInfo("117ddf31-b790-479f-a752-77c4ab4867ce")]
            public virtual RepoItemInfo EtDateBirthInfo
            {
                get
                {
                    return _etdatebirthInfo;
                }
            }

            /// <summary>
            /// The EtGender item.
            /// </summary>
            [RepositoryItem("68d14a1e-ded3-40e6-83b1-bbda76c9da82")]
            public virtual Ranorex.Text EtGender
            {
                get
                {
                    return _etgenderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtGender item info.
            /// </summary>
            [RepositoryItemInfo("68d14a1e-ded3-40e6-83b1-bbda76c9da82")]
            public virtual RepoItemInfo EtGenderInfo
            {
                get
                {
                    return _etgenderInfo;
                }
            }

            /// <summary>
            /// The BtnNext item.
            /// </summary>
            [RepositoryItem("7b133682-4665-4f25-989e-1bf1b36453f6")]
            public virtual Ranorex.Text BtnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnNext item info.
            /// </summary>
            [RepositoryItemInfo("7b133682-4665-4f25-989e-1bf1b36453f6")]
            public virtual RepoItemInfo BtnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }

            /// <summary>
            /// The BtnSkip item.
            /// </summary>
            [RepositoryItem("a846c0ca-ad31-4dd6-a433-68af9d2a5513")]
            public virtual Ranorex.Text BtnSkip
            {
                get
                {
                    return _btnskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnSkip item info.
            /// </summary>
            [RepositoryItemInfo("a846c0ca-ad31-4dd6-a433-68af9d2a5513")]
            public virtual RepoItemInfo BtnSkipInfo
            {
                get
                {
                    return _btnskipInfo;
                }
            }
        }

        /// <summary>
        /// The BarCodeScannerActivityFolder folder.
        /// </summary>
        [RepositoryFolder("311e2466-032e-4bec-9cd0-5d971b904122")]
        public partial class BarCodeScannerActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _navigateupInfo;
            RepoItemInfo _rstringbarcodescanneractionbartitlInfo;

            /// <summary>
            /// Creates a new BarCodeScannerActivity  folder.
            /// </summary>
            public BarCodeScannerActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("BarCodeScannerActivity", "form[@title='BarCodeScannerActivity']", parentFolder, 30000, null, false, "311e2466-032e-4bec-9cd0-5d971b904122", "")
            {
                _navigateupInfo = new RepoItemInfo(this, "NavigateUp", ".//button[@contentdescription='Navigate up']", 30000, null, "0b6eebff-c536-4144-8f42-b8b105376a0f");
                _rstringbarcodescanneractionbartitlInfo = new RepoItemInfo(this, "RStringBarCodeScannerActionbarTitl", ".//text[@resourceid='R.string.bar_code_scanner_actionbar_title']", 30000, null, "b27febc3-86cd-45e9-9b7d-ae2344e2b25b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("311e2466-032e-4bec-9cd0-5d971b904122")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("311e2466-032e-4bec-9cd0-5d971b904122")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateUp item.
            /// </summary>
            [RepositoryItem("0b6eebff-c536-4144-8f42-b8b105376a0f")]
            public virtual Ranorex.Button NavigateUp
            {
                get
                {
                    return _navigateupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NavigateUp item info.
            /// </summary>
            [RepositoryItemInfo("0b6eebff-c536-4144-8f42-b8b105376a0f")]
            public virtual RepoItemInfo NavigateUpInfo
            {
                get
                {
                    return _navigateupInfo;
                }
            }

            /// <summary>
            /// The RStringBarCodeScannerActionbarTitl item.
            /// </summary>
            [RepositoryItem("b27febc3-86cd-45e9-9b7d-ae2344e2b25b")]
            public virtual Ranorex.Text RStringBarCodeScannerActionbarTitl
            {
                get
                {
                    return _rstringbarcodescanneractionbartitlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringBarCodeScannerActionbarTitl item info.
            /// </summary>
            [RepositoryItemInfo("b27febc3-86cd-45e9-9b7d-ae2344e2b25b")]
            public virtual RepoItemInfo RStringBarCodeScannerActionbarTitlInfo
            {
                get
                {
                    return _rstringbarcodescanneractionbartitlInfo;
                }
            }
        }

        /// <summary>
        /// The OnBoardingStepOneActivityFolder folder.
        /// </summary>
        [RepositoryFolder("e5288b06-59df-4612-b679-57269effd9b3")]
        public partial class OnBoardingStepOneActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rstringonboardingsteponeinfotitleInfo;
            RepoItemInfo _rstringonboardingsteponedescriptioInfo;
            RepoItemInfo _btnonboardingsteponeallowInfo;
            RepoItemInfo _btnonboardingsteponeskipInfo;

            /// <summary>
            /// Creates a new OnBoardingStepOneActivity  folder.
            /// </summary>
            public OnBoardingStepOneActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("OnBoardingStepOneActivity", "form[@title='OnBoardingStepOneActivity']", parentFolder, 30000, null, false, "e5288b06-59df-4612-b679-57269effd9b3", "")
            {
                _rstringonboardingsteponeinfotitleInfo = new RepoItemInfo(this, "RStringOnBoardingStepOneInfoTitle", ".//text[@resourceid='R.string.on_boarding_step_one_info_title']", 30000, null, "51c27396-263b-43b6-815a-e627c0d77f40");
                _rstringonboardingsteponedescriptioInfo = new RepoItemInfo(this, "RStringOnBoardingStepOneDescriptio", ".//text[@resourceid='R.string.on_boarding_step_one_description']", 30000, null, "6e00b3dc-5ae1-4f7a-a35f-5743cd5c008e");
                _btnonboardingsteponeallowInfo = new RepoItemInfo(this, "BtnOnBoardingStepOneAllow", ".//text[@rid='btn_on_boarding_step_one_allow']", 30000, null, "6b6f2ff1-f022-4543-8737-6a5bc776b84b");
                _btnonboardingsteponeskipInfo = new RepoItemInfo(this, "BtnOnBoardingStepOneSkip", ".//text[@rid='btn_on_boarding_step_one_skip']", 30000, null, "48bf8886-89d9-45ca-b320-89454f662b97");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e5288b06-59df-4612-b679-57269effd9b3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e5288b06-59df-4612-b679-57269effd9b3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepOneInfoTitle item.
            /// </summary>
            [RepositoryItem("51c27396-263b-43b6-815a-e627c0d77f40")]
            public virtual Ranorex.Text RStringOnBoardingStepOneInfoTitle
            {
                get
                {
                    return _rstringonboardingsteponeinfotitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepOneInfoTitle item info.
            /// </summary>
            [RepositoryItemInfo("51c27396-263b-43b6-815a-e627c0d77f40")]
            public virtual RepoItemInfo RStringOnBoardingStepOneInfoTitleInfo
            {
                get
                {
                    return _rstringonboardingsteponeinfotitleInfo;
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepOneDescriptio item.
            /// </summary>
            [RepositoryItem("6e00b3dc-5ae1-4f7a-a35f-5743cd5c008e")]
            public virtual Ranorex.Text RStringOnBoardingStepOneDescriptio
            {
                get
                {
                    return _rstringonboardingsteponedescriptioInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepOneDescriptio item info.
            /// </summary>
            [RepositoryItemInfo("6e00b3dc-5ae1-4f7a-a35f-5743cd5c008e")]
            public virtual RepoItemInfo RStringOnBoardingStepOneDescriptioInfo
            {
                get
                {
                    return _rstringonboardingsteponedescriptioInfo;
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepOneAllow item.
            /// </summary>
            [RepositoryItem("6b6f2ff1-f022-4543-8737-6a5bc776b84b")]
            public virtual Ranorex.Text BtnOnBoardingStepOneAllow
            {
                get
                {
                    return _btnonboardingsteponeallowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepOneAllow item info.
            /// </summary>
            [RepositoryItemInfo("6b6f2ff1-f022-4543-8737-6a5bc776b84b")]
            public virtual RepoItemInfo BtnOnBoardingStepOneAllowInfo
            {
                get
                {
                    return _btnonboardingsteponeallowInfo;
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepOneSkip item.
            /// </summary>
            [RepositoryItem("48bf8886-89d9-45ca-b320-89454f662b97")]
            public virtual Ranorex.Text BtnOnBoardingStepOneSkip
            {
                get
                {
                    return _btnonboardingsteponeskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepOneSkip item info.
            /// </summary>
            [RepositoryItemInfo("48bf8886-89d9-45ca-b320-89454f662b97")]
            public virtual RepoItemInfo BtnOnBoardingStepOneSkipInfo
            {
                get
                {
                    return _btnonboardingsteponeskipInfo;
                }
            }
        }

        /// <summary>
        /// The OnBoardingStepTwoActivityFolder folder.
        /// </summary>
        [RepositoryFolder("9250a1cd-c071-4670-adfc-369fad748a97")]
        public partial class OnBoardingStepTwoActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rstringonboardingsteptwoinfotitleInfo;
            RepoItemInfo _rstringonboardingsteptwodescriptioInfo;
            RepoItemInfo _btnonboardingsteptwoallowInfo;
            RepoItemInfo _btnonboardingsteptwoskipInfo;

            /// <summary>
            /// Creates a new OnBoardingStepTwoActivity  folder.
            /// </summary>
            public OnBoardingStepTwoActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("OnBoardingStepTwoActivity", "form[@title='OnBoardingStepTwoActivity']", parentFolder, 30000, null, false, "9250a1cd-c071-4670-adfc-369fad748a97", "")
            {
                _rstringonboardingsteptwoinfotitleInfo = new RepoItemInfo(this, "RStringOnBoardingStepTwoInfoTitle", ".//text[@resourceid='R.string.on_boarding_step_two_info_title']", 30000, null, "60adb4c8-7e57-4cbb-9432-7019b0813d7b");
                _rstringonboardingsteptwodescriptioInfo = new RepoItemInfo(this, "RStringOnBoardingStepTwoDescriptio", ".//text[@resourceid='R.string.on_boarding_step_two_description']", 30000, null, "1e48ea56-a025-429f-9cf0-b8c942c16502");
                _btnonboardingsteptwoallowInfo = new RepoItemInfo(this, "BtnOnBoardingStepTwoAllow", ".//text[@rid='btn_on_boarding_step_two_allow']", 30000, null, "75f17b6f-9eb6-4064-aaf2-c98cc73eae2b");
                _btnonboardingsteptwoskipInfo = new RepoItemInfo(this, "BtnOnBoardingStepTwoSkip", ".//text[@rid='btn_on_boarding_step_two_skip']", 30000, null, "f42b2775-5bd0-4619-9f28-6f8966e4db61");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9250a1cd-c071-4670-adfc-369fad748a97")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9250a1cd-c071-4670-adfc-369fad748a97")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepTwoInfoTitle item.
            /// </summary>
            [RepositoryItem("60adb4c8-7e57-4cbb-9432-7019b0813d7b")]
            public virtual Ranorex.Text RStringOnBoardingStepTwoInfoTitle
            {
                get
                {
                    return _rstringonboardingsteptwoinfotitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepTwoInfoTitle item info.
            /// </summary>
            [RepositoryItemInfo("60adb4c8-7e57-4cbb-9432-7019b0813d7b")]
            public virtual RepoItemInfo RStringOnBoardingStepTwoInfoTitleInfo
            {
                get
                {
                    return _rstringonboardingsteptwoinfotitleInfo;
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepTwoDescriptio item.
            /// </summary>
            [RepositoryItem("1e48ea56-a025-429f-9cf0-b8c942c16502")]
            public virtual Ranorex.Text RStringOnBoardingStepTwoDescriptio
            {
                get
                {
                    return _rstringonboardingsteptwodescriptioInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepTwoDescriptio item info.
            /// </summary>
            [RepositoryItemInfo("1e48ea56-a025-429f-9cf0-b8c942c16502")]
            public virtual RepoItemInfo RStringOnBoardingStepTwoDescriptioInfo
            {
                get
                {
                    return _rstringonboardingsteptwodescriptioInfo;
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepTwoAllow item.
            /// </summary>
            [RepositoryItem("75f17b6f-9eb6-4064-aaf2-c98cc73eae2b")]
            public virtual Ranorex.Text BtnOnBoardingStepTwoAllow
            {
                get
                {
                    return _btnonboardingsteptwoallowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepTwoAllow item info.
            /// </summary>
            [RepositoryItemInfo("75f17b6f-9eb6-4064-aaf2-c98cc73eae2b")]
            public virtual RepoItemInfo BtnOnBoardingStepTwoAllowInfo
            {
                get
                {
                    return _btnonboardingsteptwoallowInfo;
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepTwoSkip item.
            /// </summary>
            [RepositoryItem("f42b2775-5bd0-4619-9f28-6f8966e4db61")]
            public virtual Ranorex.Text BtnOnBoardingStepTwoSkip
            {
                get
                {
                    return _btnonboardingsteptwoskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepTwoSkip item info.
            /// </summary>
            [RepositoryItemInfo("f42b2775-5bd0-4619-9f28-6f8966e4db61")]
            public virtual RepoItemInfo BtnOnBoardingStepTwoSkipInfo
            {
                get
                {
                    return _btnonboardingsteptwoskipInfo;
                }
            }
        }

        /// <summary>
        /// The OnBoardingStepThreeActivityFolder folder.
        /// </summary>
        [RepositoryFolder("b68303be-b644-4ef1-ad0a-2ddcfc6d5b9f")]
        public partial class OnBoardingStepThreeActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rstringonboardingstepthreeinfotitInfo;
            RepoItemInfo _rstringonboardingstepthreedescriptInfo;
            RepoItemInfo _btnonboardingstepthreefinishInfo;

            /// <summary>
            /// Creates a new OnBoardingStepThreeActivity  folder.
            /// </summary>
            public OnBoardingStepThreeActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("OnBoardingStepThreeActivity", "form[@title~'^OnBoardingStepThreeActivi']", parentFolder, 30000, null, false, "b68303be-b644-4ef1-ad0a-2ddcfc6d5b9f", "")
            {
                _rstringonboardingstepthreeinfotitInfo = new RepoItemInfo(this, "RStringOnBoardingStepThreeInfoTit", ".//text[@resourceid='R.string.on_boarding_step_three_info_title']", 30000, null, "ca674790-a066-4916-b1ef-f8e999108233");
                _rstringonboardingstepthreedescriptInfo = new RepoItemInfo(this, "RStringOnBoardingStepThreeDescript", ".//text[@resourceid='R.string.on_boarding_step_three_description']", 30000, null, "d3f29bc4-5fa0-47fa-b0c1-79ff0651d165");
                _btnonboardingstepthreefinishInfo = new RepoItemInfo(this, "BtnOnBoardingStepThreeFinish", ".//text[@rid='btn_on_boarding_step_three_finish']", 30000, null, "f683ea99-7abd-48cb-a89b-fe24c0f96e88");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b68303be-b644-4ef1-ad0a-2ddcfc6d5b9f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b68303be-b644-4ef1-ad0a-2ddcfc6d5b9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepThreeInfoTit item.
            /// </summary>
            [RepositoryItem("ca674790-a066-4916-b1ef-f8e999108233")]
            public virtual Ranorex.Text RStringOnBoardingStepThreeInfoTit
            {
                get
                {
                    return _rstringonboardingstepthreeinfotitInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepThreeInfoTit item info.
            /// </summary>
            [RepositoryItemInfo("ca674790-a066-4916-b1ef-f8e999108233")]
            public virtual RepoItemInfo RStringOnBoardingStepThreeInfoTitInfo
            {
                get
                {
                    return _rstringonboardingstepthreeinfotitInfo;
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepThreeDescript item.
            /// </summary>
            [RepositoryItem("d3f29bc4-5fa0-47fa-b0c1-79ff0651d165")]
            public virtual Ranorex.Text RStringOnBoardingStepThreeDescript
            {
                get
                {
                    return _rstringonboardingstepthreedescriptInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringOnBoardingStepThreeDescript item info.
            /// </summary>
            [RepositoryItemInfo("d3f29bc4-5fa0-47fa-b0c1-79ff0651d165")]
            public virtual RepoItemInfo RStringOnBoardingStepThreeDescriptInfo
            {
                get
                {
                    return _rstringonboardingstepthreedescriptInfo;
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepThreeFinish item.
            /// </summary>
            [RepositoryItem("f683ea99-7abd-48cb-a89b-fe24c0f96e88")]
            public virtual Ranorex.Text BtnOnBoardingStepThreeFinish
            {
                get
                {
                    return _btnonboardingstepthreefinishInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnOnBoardingStepThreeFinish item info.
            /// </summary>
            [RepositoryItemInfo("f683ea99-7abd-48cb-a89b-fe24c0f96e88")]
            public virtual RepoItemInfo BtnOnBoardingStepThreeFinishInfo
            {
                get
                {
                    return _btnonboardingstepthreefinishInfo;
                }
            }
        }

        /// <summary>
        /// The MainActivityFolder folder.
        /// </summary>
        [RepositoryFolder("04550d2f-0065-4f16-a9d6-1d6d447f1a0a")]
        public partial class MainActivityFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MainActivity  folder.
            /// </summary>
            public MainActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("MainActivity", "form[@title='MainActivity']", parentFolder, 30000, null, false, "04550d2f-0065-4f16-a9d6-1d6d447f1a0a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("04550d2f-0065-4f16-a9d6-1d6d447f1a0a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("04550d2f-0065-4f16-a9d6-1d6d447f1a0a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The EnterNumberActivityFolder folder.
        /// </summary>
        [RepositoryFolder("42a91c57-ca33-40f3-9bc1-078ca11dc89e")]
        public partial class EnterNumberActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rstringscancardentercardnumberInfo;
            RepoItemInfo _etcardnumberInfo;
            RepoItemInfo _btnnextInfo;

            /// <summary>
            /// Creates a new EnterNumberActivity  folder.
            /// </summary>
            public EnterNumberActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("EnterNumberActivity", "form[@title='EnterNumberActivity']", parentFolder, 30000, null, false, "42a91c57-ca33-40f3-9bc1-078ca11dc89e", "")
            {
                _rstringscancardentercardnumberInfo = new RepoItemInfo(this, "RStringScancardEnterCardNumber", ".//text[@resourceid='R.string.scancard_enter_card_number']", 30000, null, "72f751ed-d080-41be-a84d-fca25201c383");
                _etcardnumberInfo = new RepoItemInfo(this, "EtCardNumber", ".//text[@rid='et_card_number']", 30000, null, "05343f2e-b690-406e-9510-d7681f98c5f4");
                _btnnextInfo = new RepoItemInfo(this, "BtnNext", ".//text[@rid='btn_next']", 30000, null, "3536ecfb-e601-4c14-9964-af178c76df9b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42a91c57-ca33-40f3-9bc1-078ca11dc89e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42a91c57-ca33-40f3-9bc1-078ca11dc89e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringScancardEnterCardNumber item.
            /// </summary>
            [RepositoryItem("72f751ed-d080-41be-a84d-fca25201c383")]
            public virtual Ranorex.Text RStringScancardEnterCardNumber
            {
                get
                {
                    return _rstringscancardentercardnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringScancardEnterCardNumber item info.
            /// </summary>
            [RepositoryItemInfo("72f751ed-d080-41be-a84d-fca25201c383")]
            public virtual RepoItemInfo RStringScancardEnterCardNumberInfo
            {
                get
                {
                    return _rstringscancardentercardnumberInfo;
                }
            }

            /// <summary>
            /// The EtCardNumber item.
            /// </summary>
            [RepositoryItem("05343f2e-b690-406e-9510-d7681f98c5f4")]
            public virtual Ranorex.Text EtCardNumber
            {
                get
                {
                    return _etcardnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtCardNumber item info.
            /// </summary>
            [RepositoryItemInfo("05343f2e-b690-406e-9510-d7681f98c5f4")]
            public virtual RepoItemInfo EtCardNumberInfo
            {
                get
                {
                    return _etcardnumberInfo;
                }
            }

            /// <summary>
            /// The BtnNext item.
            /// </summary>
            [RepositoryItem("3536ecfb-e601-4c14-9964-af178c76df9b")]
            public virtual Ranorex.Text BtnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnNext item info.
            /// </summary>
            [RepositoryItemInfo("3536ecfb-e601-4c14-9964-af178c76df9b")]
            public virtual RepoItemInfo BtnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }
        }

        /// <summary>
        /// The ScanCardTermsAndConditionsFolder folder.
        /// </summary>
        [RepositoryFolder("03197287-5ad7-4b1f-b779-9b6fb51b7276")]
        public partial class ScanCardTermsAndConditionsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rstringtermsandconditionsactionbarInfo;
            RepoItemInfo _navigateupInfo;

            /// <summary>
            /// Creates a new ScanCardTermsAndConditions  folder.
            /// </summary>
            public ScanCardTermsAndConditionsFolder(RepoGenBaseFolder parentFolder) :
                    base("ScanCardTermsAndConditions", "form[@title~'^ScanCardTermsAndCondition']", parentFolder, 30000, null, false, "03197287-5ad7-4b1f-b779-9b6fb51b7276", "")
            {
                _rstringtermsandconditionsactionbarInfo = new RepoItemInfo(this, "RStringTermsAndConditionsActionbar", ".//text[@resourceid='R.string.terms_and_conditions_actionbar_title']", 30000, null, "65c40f09-e36f-435c-af0f-70f12dc75a62");
                _navigateupInfo = new RepoItemInfo(this, "NavigateUp", ".//button[@contentdescription='Navigate up']", 30000, null, "928a1aa1-6e6e-44a3-a9ad-9fe376ede62e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03197287-5ad7-4b1f-b779-9b6fb51b7276")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03197287-5ad7-4b1f-b779-9b6fb51b7276")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RStringTermsAndConditionsActionbar item.
            /// </summary>
            [RepositoryItem("65c40f09-e36f-435c-af0f-70f12dc75a62")]
            public virtual Ranorex.Text RStringTermsAndConditionsActionbar
            {
                get
                {
                    return _rstringtermsandconditionsactionbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringTermsAndConditionsActionbar item info.
            /// </summary>
            [RepositoryItemInfo("65c40f09-e36f-435c-af0f-70f12dc75a62")]
            public virtual RepoItemInfo RStringTermsAndConditionsActionbarInfo
            {
                get
                {
                    return _rstringtermsandconditionsactionbarInfo;
                }
            }

            /// <summary>
            /// The NavigateUp item.
            /// </summary>
            [RepositoryItem("928a1aa1-6e6e-44a3-a9ad-9fe376ede62e")]
            public virtual Ranorex.Button NavigateUp
            {
                get
                {
                    return _navigateupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NavigateUp item info.
            /// </summary>
            [RepositoryItemInfo("928a1aa1-6e6e-44a3-a9ad-9fe376ede62e")]
            public virtual RepoItemInfo NavigateUpInfo
            {
                get
                {
                    return _navigateupInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterStep2ResidentDataActivityFolder folder.
        /// </summary>
        [RepositoryFolder("2a0e1471-e669-4ec1-a303-48ca12e9a275")]
        public partial class RegisterStep2ResidentDataActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _etcityInfo;
            RepoItemInfo _etpostalInfo;
            RepoItemInfo _etcountryInfo;
            RepoItemInfo _ethousenumberInfo;
            RepoItemInfo _etstreetInfo;
            RepoItemInfo _btnskipInfo;
            RepoItemInfo _btnnextInfo;

            /// <summary>
            /// Creates a new RegisterStep2ResidentDataActivity  folder.
            /// </summary>
            public RegisterStep2ResidentDataActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterStep2ResidentDataActivity", "form[@title~'^RegisterStep2ResidentData']", parentFolder, 30000, null, false, "2a0e1471-e669-4ec1-a303-48ca12e9a275", "")
            {
                _etcityInfo = new RepoItemInfo(this, "EtCity", ".//text[@rid='et_city']", 30000, null, "29badc27-fd47-436e-aa01-7d05dca45367");
                _etpostalInfo = new RepoItemInfo(this, "EtPostal", ".//text[@rid='et_postal']", 30000, null, "4900b57e-195c-4152-988c-d62c4ced214b");
                _etcountryInfo = new RepoItemInfo(this, "EtCountry", ".//text[@rid='et_country']", 30000, null, "d8f78a37-b6c4-4909-82c3-ec9ab16d07d8");
                _ethousenumberInfo = new RepoItemInfo(this, "EtHouseNumber", ".//text[@rid='et_house_number']", 30000, null, "8a32bf22-f047-4166-a798-67aff6f5ac55");
                _etstreetInfo = new RepoItemInfo(this, "EtStreet", ".//text[@rid='et_street']", 30000, null, "2702edb2-9d0e-487f-8673-5c4a55c11971");
                _btnskipInfo = new RepoItemInfo(this, "BtnSkip", ".//text[@rid='btn_skip']", 30000, null, "c24858ec-ebac-49bd-972d-7478476c20b2");
                _btnnextInfo = new RepoItemInfo(this, "BtnNext", ".//text[@rid='btn_next']", 30000, null, "bea13b39-c736-4c61-834d-3c78e3dc53b0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a0e1471-e669-4ec1-a303-48ca12e9a275")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a0e1471-e669-4ec1-a303-48ca12e9a275")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EtCity item.
            /// </summary>
            [RepositoryItem("29badc27-fd47-436e-aa01-7d05dca45367")]
            public virtual Ranorex.Text EtCity
            {
                get
                {
                    return _etcityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtCity item info.
            /// </summary>
            [RepositoryItemInfo("29badc27-fd47-436e-aa01-7d05dca45367")]
            public virtual RepoItemInfo EtCityInfo
            {
                get
                {
                    return _etcityInfo;
                }
            }

            /// <summary>
            /// The EtPostal item.
            /// </summary>
            [RepositoryItem("4900b57e-195c-4152-988c-d62c4ced214b")]
            public virtual Ranorex.Text EtPostal
            {
                get
                {
                    return _etpostalInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtPostal item info.
            /// </summary>
            [RepositoryItemInfo("4900b57e-195c-4152-988c-d62c4ced214b")]
            public virtual RepoItemInfo EtPostalInfo
            {
                get
                {
                    return _etpostalInfo;
                }
            }

            /// <summary>
            /// The EtCountry item.
            /// </summary>
            [RepositoryItem("d8f78a37-b6c4-4909-82c3-ec9ab16d07d8")]
            public virtual Ranorex.Text EtCountry
            {
                get
                {
                    return _etcountryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtCountry item info.
            /// </summary>
            [RepositoryItemInfo("d8f78a37-b6c4-4909-82c3-ec9ab16d07d8")]
            public virtual RepoItemInfo EtCountryInfo
            {
                get
                {
                    return _etcountryInfo;
                }
            }

            /// <summary>
            /// The EtHouseNumber item.
            /// </summary>
            [RepositoryItem("8a32bf22-f047-4166-a798-67aff6f5ac55")]
            public virtual Ranorex.Text EtHouseNumber
            {
                get
                {
                    return _ethousenumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtHouseNumber item info.
            /// </summary>
            [RepositoryItemInfo("8a32bf22-f047-4166-a798-67aff6f5ac55")]
            public virtual RepoItemInfo EtHouseNumberInfo
            {
                get
                {
                    return _ethousenumberInfo;
                }
            }

            /// <summary>
            /// The EtStreet item.
            /// </summary>
            [RepositoryItem("2702edb2-9d0e-487f-8673-5c4a55c11971")]
            public virtual Ranorex.Text EtStreet
            {
                get
                {
                    return _etstreetInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtStreet item info.
            /// </summary>
            [RepositoryItemInfo("2702edb2-9d0e-487f-8673-5c4a55c11971")]
            public virtual RepoItemInfo EtStreetInfo
            {
                get
                {
                    return _etstreetInfo;
                }
            }

            /// <summary>
            /// The BtnSkip item.
            /// </summary>
            [RepositoryItem("c24858ec-ebac-49bd-972d-7478476c20b2")]
            public virtual Ranorex.Text BtnSkip
            {
                get
                {
                    return _btnskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnSkip item info.
            /// </summary>
            [RepositoryItemInfo("c24858ec-ebac-49bd-972d-7478476c20b2")]
            public virtual RepoItemInfo BtnSkipInfo
            {
                get
                {
                    return _btnskipInfo;
                }
            }

            /// <summary>
            /// The BtnNext item.
            /// </summary>
            [RepositoryItem("bea13b39-c736-4c61-834d-3c78e3dc53b0")]
            public virtual Ranorex.Text BtnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnNext item info.
            /// </summary>
            [RepositoryItemInfo("bea13b39-c736-4c61-834d-3c78e3dc53b0")]
            public virtual RepoItemInfo BtnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterStep3AccountDataActivityFolder folder.
        /// </summary>
        [RepositoryFolder("8c2ab8b0-4adc-4325-a95e-ad97720e7c5b")]
        public partial class RegisterStep3AccountDataActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _etphonenumberInfo;
            RepoItemInfo _etemailInfo;
            RepoItemInfo _etpasswordrepeatInfo;
            RepoItemInfo _etpasswordInfo;
            RepoItemInfo _rstringregisteraccountpasswordguidlInfo;
            RepoItemInfo _btnnextInfo;
            RepoItemInfo _btnskipInfo;
            RepoItemInfo _tvregisterloginpasswordstrengthInfo;

            /// <summary>
            /// Creates a new RegisterStep3AccountDataActivity  folder.
            /// </summary>
            public RegisterStep3AccountDataActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterStep3AccountDataActivity", "form[@title~'^RegisterStep3AccountDataA']", parentFolder, 30000, null, false, "8c2ab8b0-4adc-4325-a95e-ad97720e7c5b", "")
            {
                _etphonenumberInfo = new RepoItemInfo(this, "EtPhoneNumber", ".//text[@rid='et_phone_number']", 30000, null, "86087f93-e41d-4a52-9ff2-a6c741535ff6");
                _etemailInfo = new RepoItemInfo(this, "EtEmail", ".//text[@rid='et_email']", 30000, null, "dd8b817e-43e6-4eb3-acdd-fe4cfa613285");
                _etpasswordrepeatInfo = new RepoItemInfo(this, "EtPasswordRepeat", ".//text[@rid='et_password_repeat']", 30000, null, "a9d0dbc1-3122-4c3d-b4ea-7f4df0d9a069");
                _etpasswordInfo = new RepoItemInfo(this, "EtPassword", ".//text[@rid='et_password']", 30000, null, "b94776fd-ca45-4855-9816-4b32ed83c7f4");
                _rstringregisteraccountpasswordguidlInfo = new RepoItemInfo(this, "RStringRegisterAccountPasswordGuidl", ".//text[@resourceid='R.string.register_account_password_guidline']", 30000, null, "e8430ba9-29a4-452f-be76-7adf243f1f91");
                _btnnextInfo = new RepoItemInfo(this, "BtnNext", ".//text[@rid='btn_next']", 30000, null, "02913f13-be82-4974-9501-0a6a16b4f3be");
                _btnskipInfo = new RepoItemInfo(this, "BtnSkip", ".//text[@rid='btn_skip']", 30000, null, "b321abfd-83ed-4b64-8ff2-dd3a74be661b");
                _tvregisterloginpasswordstrengthInfo = new RepoItemInfo(this, "TvRegisterLoginPasswordStrength", ".//text[@rid='tv_register_login_password_strength']", 30000, null, "92dd8425-05a8-4e06-b42c-4aed757569f5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c2ab8b0-4adc-4325-a95e-ad97720e7c5b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c2ab8b0-4adc-4325-a95e-ad97720e7c5b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EtPhoneNumber item.
            /// </summary>
            [RepositoryItem("86087f93-e41d-4a52-9ff2-a6c741535ff6")]
            public virtual Ranorex.Text EtPhoneNumber
            {
                get
                {
                    return _etphonenumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtPhoneNumber item info.
            /// </summary>
            [RepositoryItemInfo("86087f93-e41d-4a52-9ff2-a6c741535ff6")]
            public virtual RepoItemInfo EtPhoneNumberInfo
            {
                get
                {
                    return _etphonenumberInfo;
                }
            }

            /// <summary>
            /// The EtEmail item.
            /// </summary>
            [RepositoryItem("dd8b817e-43e6-4eb3-acdd-fe4cfa613285")]
            public virtual Ranorex.Text EtEmail
            {
                get
                {
                    return _etemailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtEmail item info.
            /// </summary>
            [RepositoryItemInfo("dd8b817e-43e6-4eb3-acdd-fe4cfa613285")]
            public virtual RepoItemInfo EtEmailInfo
            {
                get
                {
                    return _etemailInfo;
                }
            }

            /// <summary>
            /// The EtPasswordRepeat item.
            /// </summary>
            [RepositoryItem("a9d0dbc1-3122-4c3d-b4ea-7f4df0d9a069")]
            public virtual Ranorex.Text EtPasswordRepeat
            {
                get
                {
                    return _etpasswordrepeatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtPasswordRepeat item info.
            /// </summary>
            [RepositoryItemInfo("a9d0dbc1-3122-4c3d-b4ea-7f4df0d9a069")]
            public virtual RepoItemInfo EtPasswordRepeatInfo
            {
                get
                {
                    return _etpasswordrepeatInfo;
                }
            }

            /// <summary>
            /// The EtPassword item.
            /// </summary>
            [RepositoryItem("b94776fd-ca45-4855-9816-4b32ed83c7f4")]
            public virtual Ranorex.Text EtPassword
            {
                get
                {
                    return _etpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtPassword item info.
            /// </summary>
            [RepositoryItemInfo("b94776fd-ca45-4855-9816-4b32ed83c7f4")]
            public virtual RepoItemInfo EtPasswordInfo
            {
                get
                {
                    return _etpasswordInfo;
                }
            }

            /// <summary>
            /// The RStringRegisterAccountPasswordGuidl item.
            /// </summary>
            [RepositoryItem("e8430ba9-29a4-452f-be76-7adf243f1f91")]
            public virtual Ranorex.Text RStringRegisterAccountPasswordGuidl
            {
                get
                {
                    return _rstringregisteraccountpasswordguidlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringRegisterAccountPasswordGuidl item info.
            /// </summary>
            [RepositoryItemInfo("e8430ba9-29a4-452f-be76-7adf243f1f91")]
            public virtual RepoItemInfo RStringRegisterAccountPasswordGuidlInfo
            {
                get
                {
                    return _rstringregisteraccountpasswordguidlInfo;
                }
            }

            /// <summary>
            /// The BtnNext item.
            /// </summary>
            [RepositoryItem("02913f13-be82-4974-9501-0a6a16b4f3be")]
            public virtual Ranorex.Text BtnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnNext item info.
            /// </summary>
            [RepositoryItemInfo("02913f13-be82-4974-9501-0a6a16b4f3be")]
            public virtual RepoItemInfo BtnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }

            /// <summary>
            /// The BtnSkip item.
            /// </summary>
            [RepositoryItem("b321abfd-83ed-4b64-8ff2-dd3a74be661b")]
            public virtual Ranorex.Text BtnSkip
            {
                get
                {
                    return _btnskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnSkip item info.
            /// </summary>
            [RepositoryItemInfo("b321abfd-83ed-4b64-8ff2-dd3a74be661b")]
            public virtual RepoItemInfo BtnSkipInfo
            {
                get
                {
                    return _btnskipInfo;
                }
            }

            /// <summary>
            /// The TvRegisterLoginPasswordStrength item.
            /// </summary>
            [RepositoryItem("92dd8425-05a8-4e06-b42c-4aed757569f5")]
            public virtual Ranorex.Text TvRegisterLoginPasswordStrength
            {
                get
                {
                    return _tvregisterloginpasswordstrengthInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TvRegisterLoginPasswordStrength item info.
            /// </summary>
            [RepositoryItemInfo("92dd8425-05a8-4e06-b42c-4aed757569f5")]
            public virtual RepoItemInfo TvRegisterLoginPasswordStrengthInfo
            {
                get
                {
                    return _tvregisterloginpasswordstrengthInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterStep4AdditionalDataActivityFolder folder.
        /// </summary>
        [RepositoryFolder("8625c355-2d72-4d5a-819d-ef0b52abe409")]
        public partial class RegisterStep4AdditionalDataActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnnextInfo;
            RepoItemInfo _btnskipInfo;
            RepoItemInfo _swdirectmailInfo;
            RepoItemInfo _swphoneInfo;
            RepoItemInfo _tvemailInfo;
            RepoItemInfo _swsparappInfo;
            RepoItemInfo _etchildrenInfo;
            RepoItemInfo _ethouseholdnumberInfo;

            /// <summary>
            /// Creates a new RegisterStep4AdditionalDataActivity  folder.
            /// </summary>
            public RegisterStep4AdditionalDataActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterStep4AdditionalDataActivity", "form[@title~'^RegisterStep4AdditionalDa']", parentFolder, 30000, null, false, "8625c355-2d72-4d5a-819d-ef0b52abe409", "")
            {
                _btnnextInfo = new RepoItemInfo(this, "BtnNext", ".//text[@rid='btn_next']", 30000, null, "f6a02fd7-e788-4ed5-a98c-571bb1b28315");
                _btnskipInfo = new RepoItemInfo(this, "BtnSkip", ".//text[@rid='btn_skip']", 30000, null, "6c08893b-189d-462e-bda6-4e0e5d8fb27f");
                _swdirectmailInfo = new RepoItemInfo(this, "SwDirectMail", ".//button[@rid='sw_direct_mail']", 30000, null, "8f078ddd-997e-4076-9266-1f4582d6f9b4");
                _swphoneInfo = new RepoItemInfo(this, "SwPhone", ".//button[@rid='sw_phone']", 30000, null, "fe6835d6-dbe3-4cea-a55e-e838f5acd4ee");
                _tvemailInfo = new RepoItemInfo(this, "TvEmail", ".//text[@rid='tv_email']", 30000, null, "b64d46d1-a6ab-4899-a194-0a9e9e5bc8a6");
                _swsparappInfo = new RepoItemInfo(this, "SwSparApp", ".//button[@rid='sw_spar_app']", 30000, null, "7d304b31-58e4-4e00-aecd-b6a8279b185e");
                _etchildrenInfo = new RepoItemInfo(this, "EtChildren", ".//text[@rid='et_children']", 30000, null, "bc028cc7-e3d0-4548-b391-6e83e6444602");
                _ethouseholdnumberInfo = new RepoItemInfo(this, "EtHouseholdNumber", ".//text[@rid='et_household_number']", 30000, null, "8bd84c81-8aa0-4aed-a1a9-e662c363b73e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8625c355-2d72-4d5a-819d-ef0b52abe409")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8625c355-2d72-4d5a-819d-ef0b52abe409")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnNext item.
            /// </summary>
            [RepositoryItem("f6a02fd7-e788-4ed5-a98c-571bb1b28315")]
            public virtual Ranorex.Text BtnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnNext item info.
            /// </summary>
            [RepositoryItemInfo("f6a02fd7-e788-4ed5-a98c-571bb1b28315")]
            public virtual RepoItemInfo BtnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }

            /// <summary>
            /// The BtnSkip item.
            /// </summary>
            [RepositoryItem("6c08893b-189d-462e-bda6-4e0e5d8fb27f")]
            public virtual Ranorex.Text BtnSkip
            {
                get
                {
                    return _btnskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnSkip item info.
            /// </summary>
            [RepositoryItemInfo("6c08893b-189d-462e-bda6-4e0e5d8fb27f")]
            public virtual RepoItemInfo BtnSkipInfo
            {
                get
                {
                    return _btnskipInfo;
                }
            }

            /// <summary>
            /// The SwDirectMail item.
            /// </summary>
            [RepositoryItem("8f078ddd-997e-4076-9266-1f4582d6f9b4")]
            public virtual Ranorex.Button SwDirectMail
            {
                get
                {
                    return _swdirectmailInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwDirectMail item info.
            /// </summary>
            [RepositoryItemInfo("8f078ddd-997e-4076-9266-1f4582d6f9b4")]
            public virtual RepoItemInfo SwDirectMailInfo
            {
                get
                {
                    return _swdirectmailInfo;
                }
            }

            /// <summary>
            /// The SwPhone item.
            /// </summary>
            [RepositoryItem("fe6835d6-dbe3-4cea-a55e-e838f5acd4ee")]
            public virtual Ranorex.Button SwPhone
            {
                get
                {
                    return _swphoneInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwPhone item info.
            /// </summary>
            [RepositoryItemInfo("fe6835d6-dbe3-4cea-a55e-e838f5acd4ee")]
            public virtual RepoItemInfo SwPhoneInfo
            {
                get
                {
                    return _swphoneInfo;
                }
            }

            /// <summary>
            /// The TvEmail item.
            /// </summary>
            [RepositoryItem("b64d46d1-a6ab-4899-a194-0a9e9e5bc8a6")]
            public virtual Ranorex.Text TvEmail
            {
                get
                {
                    return _tvemailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TvEmail item info.
            /// </summary>
            [RepositoryItemInfo("b64d46d1-a6ab-4899-a194-0a9e9e5bc8a6")]
            public virtual RepoItemInfo TvEmailInfo
            {
                get
                {
                    return _tvemailInfo;
                }
            }

            /// <summary>
            /// The SwSparApp item.
            /// </summary>
            [RepositoryItem("7d304b31-58e4-4e00-aecd-b6a8279b185e")]
            public virtual Ranorex.Button SwSparApp
            {
                get
                {
                    return _swsparappInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwSparApp item info.
            /// </summary>
            [RepositoryItemInfo("7d304b31-58e4-4e00-aecd-b6a8279b185e")]
            public virtual RepoItemInfo SwSparAppInfo
            {
                get
                {
                    return _swsparappInfo;
                }
            }

            /// <summary>
            /// The EtChildren item.
            /// </summary>
            [RepositoryItem("bc028cc7-e3d0-4548-b391-6e83e6444602")]
            public virtual Ranorex.Text EtChildren
            {
                get
                {
                    return _etchildrenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtChildren item info.
            /// </summary>
            [RepositoryItemInfo("bc028cc7-e3d0-4548-b391-6e83e6444602")]
            public virtual RepoItemInfo EtChildrenInfo
            {
                get
                {
                    return _etchildrenInfo;
                }
            }

            /// <summary>
            /// The EtHouseholdNumber item.
            /// </summary>
            [RepositoryItem("8bd84c81-8aa0-4aed-a1a9-e662c363b73e")]
            public virtual Ranorex.Text EtHouseholdNumber
            {
                get
                {
                    return _ethouseholdnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtHouseholdNumber item info.
            /// </summary>
            [RepositoryItemInfo("8bd84c81-8aa0-4aed-a1a9-e662c363b73e")]
            public virtual RepoItemInfo EtHouseholdNumberInfo
            {
                get
                {
                    return _ethouseholdnumberInfo;
                }
            }
        }

        /// <summary>
        /// The LoginEmailSentActivityFolder folder.
        /// </summary>
        [RepositoryFolder("138292e3-349e-40be-ad83-efa673a0e21f")]
        public partial class LoginEmailSentActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnemailsentskipInfo;

            /// <summary>
            /// Creates a new LoginEmailSentActivity  folder.
            /// </summary>
            public LoginEmailSentActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginEmailSentActivity", "form[@title='LoginEmailSentActivity']", parentFolder, 30000, null, false, "138292e3-349e-40be-ad83-efa673a0e21f", "")
            {
                _btnemailsentskipInfo = new RepoItemInfo(this, "BtnEmailSentSkip", ".//text[@rid='btn_email_sent_skip']", 30000, null, "c2955545-b608-4227-acc1-cb48909ed7a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("138292e3-349e-40be-ad83-efa673a0e21f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("138292e3-349e-40be-ad83-efa673a0e21f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnEmailSentSkip item.
            /// </summary>
            [RepositoryItem("c2955545-b608-4227-acc1-cb48909ed7a2")]
            public virtual Ranorex.Text BtnEmailSentSkip
            {
                get
                {
                    return _btnemailsentskipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BtnEmailSentSkip item info.
            /// </summary>
            [RepositoryItemInfo("c2955545-b608-4227-acc1-cb48909ed7a2")]
            public virtual RepoItemInfo BtnEmailSentSkipInfo
            {
                get
                {
                    return _btnemailsentskipInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}