///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.MySpar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeLanguage recording.
    /// </summary>
    [TestModule("4bff16a2-15b5-459d-bca2-c553cfc20104", ModuleType.Recording, 1)]
    public partial class ChangeLanguage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static ChangeLanguage instance = new ChangeLanguage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeLanguage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeLanguage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MenuBtnMySpar' at Center", repo.PlusSparSi.MainActivity.MySpar.MenuBtnMySparInfo, new RecordItemIndex(0));
            repo.PlusSparSi.MainActivity.MySpar.MenuBtnMySpar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.ImgUserProfile' at Center", repo.PlusSparSi.MainActivity.MySpar.ImgUserProfileInfo, new RecordItemIndex(1));
            repo.PlusSparSi.MainActivity.MySpar.ImgUserProfile.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelections' at Center", repo.PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelectionsInfo, new RecordItemIndex(2));
            repo.PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelections.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Slovenščina') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.Slovenian'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.SlovenianInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.SlovenianInfo, "Text", "Slovenščina");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='English') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.English'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.EnglishInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.EnglishInfo, "Text", "English");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MyProfile.Slovenian' at Center", repo.PlusSparSi.MainActivity.MySpar.MyProfile.SlovenianInfo, new RecordItemIndex(5));
            repo.PlusSparSi.MainActivity.MySpar.MyProfile.Slovenian.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.MainActivity.MySpar.MyProfile.ImgCheckmarkSlo'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.ImgCheckmarkSloInfo, new RecordItemIndex(6));
            Validate.Exists(repo.PlusSparSi.MainActivity.MySpar.MyProfile.ImgCheckmarkSloInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.KrmarjenjeNavzgor' at Center", repo.PlusSparSi.MainActivity.KrmarjenjeNavzgorInfo, new RecordItemIndex(7));
            repo.PlusSparSi.MainActivity.KrmarjenjeNavzgor.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Izbira jezika') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.IzbiraJezika'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.IzbiraJezikaInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.IzbiraJezikaInfo, "Text", "Izbira jezika");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MyProfile.IzbiraJezika' at Center", repo.PlusSparSi.MainActivity.MySpar.MyProfile.IzbiraJezikaInfo, new RecordItemIndex(9));
            repo.PlusSparSi.MainActivity.MySpar.MyProfile.IzbiraJezika.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MyProfile.English' at Center", repo.PlusSparSi.MainActivity.MySpar.MyProfile.EnglishInfo, new RecordItemIndex(10));
            repo.PlusSparSi.MainActivity.MySpar.MyProfile.English.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.MainActivity.MySpar.MyProfile.ImgCheckmarkEng'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.ImgCheckmarkEngInfo, new RecordItemIndex(11));
            Validate.Exists(repo.PlusSparSi.MainActivity.MySpar.MyProfile.ImgCheckmarkEngInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Language Selection') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelections'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelectionsInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelectionsInfo, "Text", "Language Selection");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
