///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.MySpar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MySpar_Guest_Overview recording.
    /// </summary>
    [TestModule("aa4391ec-f76d-453d-b148-7c6b889aa29a", ModuleType.Recording, 1)]
    public partial class MySpar_Guest_Overview : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static MySpar_Guest_Overview instance = new MySpar_Guest_Overview();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MySpar_Guest_Overview()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MySpar_Guest_Overview Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MenuBtnMySpar' at Center", repo.PlusSparSi.MainActivity.MySpar.MenuBtnMySparInfo, new RecordItemIndex(0));
            repo.PlusSparSi.MainActivity.MySpar.MenuBtnMySpar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='My SPAR plus card') on item 'PlusSparSi.MainActivity.MySpar.MySPARPlusCard'.", repo.PlusSparSi.MainActivity.MySpar.MySPARPlusCardInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MySPARPlusCardInfo, "Text", "My SPAR plus card");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.MainActivity.MySpar.SAMPLE'.", repo.PlusSparSi.MainActivity.MySpar.SAMPLEInfo, new RecordItemIndex(2));
            Validate.Exists(repo.PlusSparSi.MainActivity.MySpar.SAMPLEInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.MainActivity.MySpar.Img25Discount'.", repo.PlusSparSi.MainActivity.MySpar.Img25DiscountInfo, new RecordItemIndex(3));
            Validate.Exists(repo.PlusSparSi.MainActivity.MySpar.Img25DiscountInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sign up and get your coupons in the mobile app.') on item 'PlusSparSi.MainActivity.MySpar.SignUpAndGetYourCoupons'.", repo.PlusSparSi.MainActivity.MySpar.SignUpAndGetYourCouponsInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.SignUpAndGetYourCouponsInfo, "Text", "Sign up and get your coupons in the mobile app.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sign up') on item 'PlusSparSi.MainActivity.MySpar.SignUp'.", repo.PlusSparSi.MainActivity.MySpar.SignUpInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.SignUpInfo, "Text", "Sign up");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.MainActivity.MySpar.ImgUserProfile'.", repo.PlusSparSi.MainActivity.MySpar.ImgUserProfileInfo, new RecordItemIndex(6));
            Validate.Exists(repo.PlusSparSi.MainActivity.MySpar.ImgUserProfileInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.ImgUserProfile' at Center", repo.PlusSparSi.MainActivity.MySpar.ImgUserProfileInfo, new RecordItemIndex(7));
            repo.PlusSparSi.MainActivity.MySpar.ImgUserProfile.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='My Profile') on item 'PlusSparSi.MainActivity.MySpar.MyProfileTitle'.", repo.PlusSparSi.MainActivity.MySpar.MyProfileTitleInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfileTitleInfo, "Text", "My Profile");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.MainActivity.MySpar.AndroidSupportV7WidgetAppCompatImage'.", repo.PlusSparSi.MainActivity.MySpar.AndroidSupportV7WidgetAppCompatImageInfo, new RecordItemIndex(9));
            Validate.Exists(repo.PlusSparSi.MainActivity.MySpar.AndroidSupportV7WidgetAppCompatImageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Scan') on item 'PlusSparSi.MainActivity.MySpar.BtnMySparScan'.", repo.PlusSparSi.MainActivity.MySpar.BtnMySparScanInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.BtnMySparScanInfo, "Text", "Scan");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='I don't own a card') on item 'PlusSparSi.ScanCardActivity.BtnNoCard'.", repo.PlusSparSi.ScanCardActivity.BtnNoCardInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.PlusSparSi.ScanCardActivity.BtnNoCardInfo, "Text", "I don't own a card");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Problems with scanning your card?') on item 'PlusSparSi.MainActivity.MySpar.ProblemsWithScanningText'.", repo.PlusSparSi.MainActivity.MySpar.ProblemsWithScanningTextInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.ProblemsWithScanningTextInfo, "Text", "Problems with scanning your card?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Enter card serial number') on item 'PlusSparSi.ScanCardActivity.BtnManualInsertCardNumber'.", repo.PlusSparSi.ScanCardActivity.BtnManualInsertCardNumberInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.PlusSparSi.ScanCardActivity.BtnManualInsertCardNumberInfo, "Text", "Enter card serial number");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Push Notifications') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.PushNotification'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.PushNotificationInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.PushNotificationInfo, "Text", "Push Notifications");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Ask Us') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.AskUs'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.AskUsInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.AskUsInfo, "Text", "Ask Us");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Language Selection') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelections'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelectionsInfo, new RecordItemIndex(16));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.LanguageSelectionsInfo, "Text", "Language Selection");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Help and Advice') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.HelpAndAdvice'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.HelpAndAdviceInfo, new RecordItemIndex(17));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.HelpAndAdviceInfo, "Text", "Help and Advice");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='About') on item 'PlusSparSi.MainActivity.MySpar.MyProfile.About'.", repo.PlusSparSi.MainActivity.MySpar.MyProfile.AboutInfo, new RecordItemIndex(18));
            Validate.Attribute(repo.PlusSparSi.MainActivity.MySpar.MyProfile.AboutInfo, "Text", "About");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
