///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.MySpar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MySpar_Login_IncorrectSN recording.
    /// </summary>
    [TestModule("3f514427-a3f2-4d74-93ea-7706b9c33122", ModuleType.Recording, 1)]
    public partial class MySpar_Login_IncorrectSN : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static MySpar_Login_IncorrectSN instance = new MySpar_Login_IncorrectSN();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MySpar_Login_IncorrectSN()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MySpar_Login_IncorrectSN Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MenuBtnMySpar' at Center", repo.PlusSparSi.MainActivity.MySpar.MenuBtnMySparInfo, new RecordItemIndex(0));
            repo.PlusSparSi.MainActivity.MySpar.MenuBtnMySpar.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.ImgUserProfile' at Center", repo.PlusSparSi.MainActivity.MySpar.ImgUserProfileInfo, new RecordItemIndex(1));
            repo.PlusSparSi.MainActivity.MySpar.ImgUserProfile.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.MainActivity.MySpar.MyProfile.BtnMySparManualInsertCardNr' at Center", repo.PlusSparSi.MainActivity.MySpar.MyProfile.BtnMySparManualInsertCardNrInfo, new RecordItemIndex(2));
            repo.PlusSparSi.MainActivity.MySpar.MyProfile.BtnMySparManualInsertCardNr.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '01010101' on item 'PlusSparSi.EnterNumberActivity.EtCardNumber'.", repo.PlusSparSi.EnterNumberActivity.EtCardNumberInfo, new RecordItemIndex(3));
            repo.PlusSparSi.EnterNumberActivity.EtCardNumber.Element.SetAttributeValue("Text", "01010101");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.EnterNumberActivity.BtnNext' at Center", repo.PlusSparSi.EnterNumberActivity.BtnNextInfo, new RecordItemIndex(4));
            repo.PlusSparSi.EnterNumberActivity.BtnNext.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlusSparSi.InvalidCardOrScanError.AndroidSupportV7WidgetAppCompatImage'.", repo.PlusSparSi.InvalidCardOrScanError.AndroidSupportV7WidgetAppCompatImageInfo, new RecordItemIndex(5));
            Validate.Exists(repo.PlusSparSi.InvalidCardOrScanError.AndroidSupportV7WidgetAppCompatImageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Invalid SPAR plus loyalty card or scanning error') on item 'PlusSparSi.InvalidCardOrScanError.RStringInvalidCardOrScanErrorInfo'.", repo.PlusSparSi.InvalidCardOrScanError.RStringInvalidCardOrScanErrorInfoInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.PlusSparSi.InvalidCardOrScanError.RStringInvalidCardOrScanErrorInfoInfo, "Text", "Invalid SPAR plus loyalty card or scanning error");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='If you need help you can call us at the toll free number 080 82 44 (weekdays from 8:00 to 20:00).') on item 'PlusSparSi.InvalidCardOrScanError.RStringInvalidCardOrScanErrorDesc'.", repo.PlusSparSi.InvalidCardOrScanError.RStringInvalidCardOrScanErrorDescInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.PlusSparSi.InvalidCardOrScanError.RStringInvalidCardOrScanErrorDescInfo, "Text", "If you need help you can call us at the toll free number 080 82 44 (weekdays from 8:00 to 20:00).");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Re-enter') on item 'PlusSparSi.InvalidCardOrScanError.BtnRetry'.", repo.PlusSparSi.InvalidCardOrScanError.BtnRetryInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.PlusSparSi.InvalidCardOrScanError.BtnRetryInfo, "Text", "Re-enter");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.InvalidCardOrScanError.BtnRetry' at Center", repo.PlusSparSi.InvalidCardOrScanError.BtnRetryInfo, new RecordItemIndex(9));
            repo.PlusSparSi.InvalidCardOrScanError.BtnRetry.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Enter card serial number') on item 'PlusSparSi.EnterNumberActivity.RStringScancardEnterCardNumber'.", repo.PlusSparSi.EnterNumberActivity.RStringScancardEnterCardNumberInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.PlusSparSi.EnterNumberActivity.RStringScancardEnterCardNumberInfo, "Text", "Enter card serial number");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PlusSparSi.EnterNumberActivity.NavigateUp' at Center", repo.PlusSparSi.EnterNumberActivity.NavigateUpInfo, new RecordItemIndex(11));
            repo.PlusSparSi.EnterNumberActivity.NavigateUp.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
